#! /bin/bash
# This file is part of ee9 (V5), the GNU Ada emulator of the English Electric KDF9.
# Copyright (C) 2020, W. Findlay; all rights reserved.
#
# The ee9 system is free software; you can redistribute it and/or
# modify it under terms of the GNU General Public License as published
# by the Free Software Foundation; either version 3, or (at your option)
# any later version. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have
# received a copy of the GNU General Public License distributed with
# this program; see file COPYING. If not, see <http://www.gnu.org/licenses/>.

ROOT=..
A=${ROOT}/Adjuncts
B=${ROOT}/Build
S=${ROOT}/Source
T=${ROOT}/Testing
U=${T}/Assembly
X=${T}/Binary
K=${T}/Kidsgrove
W=${T}/Whetstone

echo de40ine will work with folders in `pwd`/..
echo Is this what you want\?
echo "If not, Press q to quit: "

read reply
case ${reply} in
q|Q) exit 0
     ;;
*) ;;
esac

/usr/bin/xattr -d com.apple.quarantine ..
/usr/bin/xattr -d com.apple.quarantine .

/usr/bin/xattr -r -d com.apple.quarantine ${A}
/usr/bin/xattr -r -d com.apple.quarantine ${B}
/usr/bin/xattr -r -d com.apple.quarantine ${S}
/usr/bin/xattr -r -d com.apple.quarantine ${T}
/usr/bin/xattr -r -d com.apple.quarantine ${U}
/usr/bin/xattr -r -d com.apple.quarantine ${A}
/usr/bin/xattr -r -d com.apple.quarantine ${K}
/usr/bin/xattr -r -d com.apple.quarantine ${W}

echo The ee9 system is now out of quarantine. Stay safe!
