PROGRAM TEST3 (OUTPUT);
TYPE
   ADDRESS = INTEGER;
   POSRANGE = 1..5;
   NEGRANGE = -5..-1;
VAR
   INTARRAY : ARRAY[POSRANGE] OF INTEGER;
   BYTEARRAY : PACKED ARRAY[NEGRANGE] OF 0..255;
   CHARARRAY : ARRAY[POSRANGE] OF CHAR;
   STRING : PACKED ARRAY[POSRANGE] OF CHAR;
   BOOLARRAY : ARRAY[NEGRANGE] OF BOOLEAN;
   BITSTRING : PACKED ARRAY[POSRANGE] OF BOOLEAN;
   REALARRAY : PACKED ARRAY[NEGRANGE] OF REAL;
   PTRARRAY : ARRAY[POSRANGE] OF ^POSRANGE;
   PACKEDPTRARRAY : PACKED ARRAY[NEGRANGE] OF ^ NEGRANGE;
   POS : POSRANGE;

   PROCEDURE INVALIDATE (A : ADDRESS);
      BEGIN
      STOREWORDAT(-MAXINT, A);
      STOREWORDAT(WORDAT(A)-1, A);
      END (*INVALIDATE*);

BEGIN (* TEST3 *)
FOR POS := 1 TO 5 DO
   BEGIN
   INVALIDATE(ADDRESSOF(INTARRAY[POS]));
   INVALIDATE(ADDRESSOF(CHARARRAY[POS]));
   INVALIDATE(ADDRESSOF(BOOLARRAY[-POS]));
   INVALIDATE(ADDRESSOF(REALARRAY[-POS]));
   IF ODD(POS) THEN
      NEW(PTRARRAY[POS])
   ELSE
      INVALIDATE(ADDRESSOF(PTRARRAY[POS]));
   IF ODD(POS) THEN
      INVALIDATE(ADDRESSOF(PACKEDPTRARRAY[-POS]))
   ELSE
      NEW(PACKEDPTRARRAY[-POS]);
   BYTEARRAY[-POS] := POS;
   STRING[POS] := CHR(ORD('A') + POS - 1);
   BITSTRING[POS] := ODD(POS);
   END;
FOR POS := 2 TO 4 DO
   BEGIN
   INTARRAY[POS] := POS;
   CHARARRAY[POS] := CHR(ORD('A' ) + POS-1);
   BOOLARRAY[-POS] := ODD(POS);
   REALARRAY[-POS] := 1.0/POS;
   END;
(* FAIL *)
RESET(OUTPUT);
END (* TEST3 *) .
