#!/bin/bash
BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data

if [ x"$1"x = xx ]
then
    echo "You have not named a binary program to be run."
    echo
    exit 1
fi

program=`basename "$1"`
program=${BINARY}/"$program"
if [ ! -r "$program" ]
then
    echo "The object code file "$program" is absent or unreadable."
    echo
    exit 2
fi

if [ x"$2"x = xx -o x"$2"x = x-x ]
then
    >${KDF9ROOT}/CR0
else
    data=${DATA}/`basename "$2" .txt`.txt
    if [ -r "$data" ]
    then
        cat "$data" > ${KDF9ROOT}/CR0
    else
        echo "The data file "$data" is absent or unreadable."
        echo
        exit 3
    fi
fi

mode=-d$3
miscellany=-m$4
if   [ "$mode" = -d ]
then
    ${KDF9ROOT}/ee9 -sp -df "$miscellany" +"$program";
elif [ "$3" = - ]
then
   ${KDF9ROOT}/ee9 -sp -df "$miscellany" +"$program";
elif [ "$mode" = -df ]
then
    time ${KDF9ROOT}/ee9 -sp -df "$miscellany" +"$program";
else
    ${KDF9ROOT}/ee9 -sp "$mode" "$miscellany"  +"$program";
fi

${KDF9ROOT}/printoutput