#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# dumptape : Displays the contents of a tape drive using mtp and
#            converting the output to UTF8
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT = "~/.kdf9/"
fi

KDF9BIN=${KDF9ROOT}

TMPFILE=/tmp/mtp.dump

trap "rm -f ${TMPFILE}" 0 1 2 3

${KDF9BIN}/mtp $1 $2 $3 $4 > ${TMPFILE}

if [ -s ${TMPFILE} ] 
then
    iconv -f `file -b --mime-encoding ${TMPFILE}` -t UTF8 < ${TMPFILE}; >/dev/null
fi

