#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# kalgol : compiles a60 to usercode and then onto a binary
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT = "~/.kdf9/"
fi

KDF9BIN=${KDF9ROOT}

SOURCE=${KDF9ROOT}/Kidsgrove
DATA=${KDF9ROOT}/Data
BINARY=${KDF9ROOT}/Binary
LOGS=${KDF9ROOT}/logs
SETTINGS=${KDF9ROOT}/settings
USERCODE=${KDF9ROOT}/Assembly

trap "rm -f  /tmp/chan6.pt /tmp/ptp.bin /tmp/mt.out /tmp/punch.txt;
      rm -f  ${DATA}/systape.txt ${DATA}/ABS_text.txt"   \
      0 1 2 3
      
trap " >${KDF9ROOT}/MT0 >${KDF9ROOT}/MT1 >${KDF9ROOT}/MT2 >${KDF9ROOT}/MT3 >${KDF9ROOT}/MT4
       >${KDF9ROOT}/MT5 >${KDF9ROOT}/MT6 >${KDF9ROOT}/MT7
       >${KDF9ROOT}/TR0 >${KDF9ROOT}/TR1 " 0

if [ x${KIDSMODE}x = xfx ]
then
   KIDSMODE=""
fi

if [ x$1x = xx ]
then
   echo No program name was given.; echo
   exit 1
elif [ ! -r ${SOURCE}/$1.a60 ]
then
   echo The file ${SOURCE}/$1.a60 is absent or unreadable.; echo
   exit 1
else
   name=$1
fi

> ${KDF9ROOT}/settings_1.txt

${KDF9BIN}/rlt tape_labels_for_KAlgol - wz
#echo "The compiler work tapes have been labelled."

cat ${DATA}/systape_kalgol.txt > ${DATA}/systape.txt

${KDF9BIN}/nine MKSYS2 systape - wz
#echo "The compiler overlay tape has been generated."; echo

${KDF9ROOT}/mkchan ${SOURCE}/$name.a60 /tmp/chan6.pt > /dev/null
#echo "The basic symbol source program tape has been made."; echo

> ${KDF9ROOT}/TP0
rm -f ${BINARY}/$name
rm -f ${USERCODE}/$name.k3
cat /tmp/chan6.pt > ${DATA}/ABS_text.txt
#chmod 755 ${KDF9ROOT}/TR0

cat ${SETTINGS}/settings_for_kalgol.txt > ${KDF9ROOT}/settings_1.txt

shift
if [ x"$1"x == "xwithx" -o x"$1"x == "xWITHx" ]
then
   shift
fi
${KDF9ROOT}/kidopt with $* ${KIDSOPTS} >> ${KDF9ROOT}/settings_1.txt

if ${KDF9BIN}/nine KAB00DH--USU ${DATA}/ABS_text ${KIDSMODE:--} ${KIDSMISC:-w-} ll kk 2> ${LOGS}/error_output
then
   if [ -s ${LOGS}/error_output ]
   then
      echo "The compilation was abandoned."; echo
      echo "${LOGS}/error_output":
      echo "==="
      more "${LOGS}/error_output"
      echo "==="
      exit 2
      exit 999
   fi

   if fgrep FAIL ${KDF9ROOT}/LP0 >/dev/null  2>/dev/null
   then
      echo "The compilation was abandoned."; echo
      echo "LP0:"
      echo "==="
      more "${KDF9ROOT}/LP0"
      echo "==="
      exit 2
   fi

   if fgrep FAIL ${KDF9ROOT}/TP0 >/dev/null  2>/dev/null
   then
      echo "The compilation was abandoned."; echo
      echo "TP0:"
      echo "==="
      more "${KDF9ROOT}/TP0"
      echo "==="
      exit 3
   fi

fi

#${KDF9ROOT}/a2b -p2t < TP0 > ${USERCODE}/$name.k3
${KDF9BIN}/mtp MT0T > ${USERCODE}/$name.k3

if [ ! -s ${USERCODE}/$name.k3 ]
then
   echo "The Usercode object program could not be retrieved."; echo; echo
   exit 4
fi

case ${KIDSGROVE_ASSEMBLY:-y} in
y)
   ${KDF9BIN}/neat$name ${ST:-24000} ${TL:-99999}
   ${KDF9BIN}/ucc $name
   if [ ! -s ${BINARY}/$name ]
   then
      echo "An object program could not be assembled."; echo; echo
      exit 5
   fi
   echo "The Usercode is in ${USERCODE}/$name.k3 and the KDF9 executable is in ${BINARY}/$name"; echo
   ;;
*)
   ;;
esac
