#!/bin/bash
SOURCE=${KDF9ROOT}/Kidsgrove
DATA=${KDF9ROOT}/Data
TESTS=${KDF9ROOT}/tests
BINARY=${KDF9ROOT}/Binary
LOGS=${KDF9ROOT}/Logs
SETTINGS=${KDF9ROOT}/settings

trap "rm -f  /tmp/chan6.pt /tmp/ptp.bin /tmp/mt.out /tmp/punch.txt ${LOGS}/error_output;
      rm -f  ${DATA}/kalgol_labels.txt ${DATA}/ABS_text.txt"   \
      0 1 2 3
      
if [ x${KIDSMODE}x = xfx ]
then
   KIDSMODE=""
fi

if [ x$1x = xx ]
then
   echo No program name was given.; echo
   exit 1
elif [ ! -r ${SOURCE}/$1.a60 ]
then
   echo The file ${SOURCE}/$1.a60 is absent or unreadable.; echo
   exit 1
else
   name=$1
fi

> ${KDF9ROOT}/settings_1.txt

cat > ${DATA}/kalgol_labels.txt <<++++
00000000        |
00000001        |
00000002        |
00000003        |
00000004        |
00000005        |
|
++++

${KDF9ROOT}/nine_test RLT {DATA}/kalgol_labels - zw
#echo "The compiler work tapes have been labelled."

${KDF9ROOT}/nine MKSYS2 systape - wz
#echo "The compiler overlay tape has been generated."; echo

${KDF9ROOT}/mkchan ${SOURCE}/$name.a60 /tmp/chan6.pt > /dev/null
#echo "The basic symbol source program tape has been made."; echo

> ${KDF9ROOT}/TP0
rm -f ${BINARY}/$name
rm -f ${USERCODE}/$name.k3
cp /tmp/chan6.pt ${DATA}/ABS_text.txt
chmod 755 ${KDF9ROOT}/TR0

cp -f ${SETTINGS}/settings_for_kalgol.txt ${KDF9ROOT}/settings_1.txt

shift
if [ x"$1"x == "xwithx" -o x"$1"x == "xWITHx" ]
then
   shift
fi
${KDF9ROOT}/kidopt with $* ${KIDSOPTS} >> ${KDF9ROOT}/settings_1.txt

if ${KDF9ROOT}/nine KAB00DH--USU ${DATA}/ABS_text ${KIDSMODE:--} ${KIDSMISC:-w-} ll kk 2> ${LOGS}/error_output
then
   if [ -s ${LOGS}/error_output ]
   then
      echo The compilation was abandoned.; printf "\\a\\a\\a"
      echo ${LOGS}/error_output:
      echo ===
      more ${LOGS}/error_output
      echo ===
      exit 2
      exit 999
   fi

   if fgrep FAIL ${KDF9ROOT}/LP0 >/dev/null  2>/dev/null
   then
      echo The compilation was abandoned.; printf "\\a\\a\\a"
      echo LP0:
      echo ===
      more ${KDF9ROOT}/LP0
      echo ===
      exit 2
   fi

   if fgrep FAIL ${KDF9ROOT}/TP0 >/dev/null  2>/dev/null
   then
      echo The compilation was abandoned.; printf "\\a\\a\\a"
      echo TP0:
      echo ===
      more ${KDF9ROOT}/TP0
      echo ===
      exit 3
   fi

fi

# a2b -p2t < TP0 > ${USERCODE}/$name.k3
${KDF9ROOT}/mtp MT0T > ${USERCODE}/$name.k3

if [ ! -s ${USERCODE}/$name.k3 ]
then
   echo The Usercode object program could not be retrieved.; printf "\\a\\a\\a"; echo
   exit 4
fi

case ${KIDSGROVE_ASSEMBLY:-y} in
y)
   ${KDF9ROOT}/neat $name ${ST:-24000} ${TL:-99999}
   ${KDF9ROOT}/ucc $name
   if [ ! -s ${BINARY}/$name ]
   then
      echo An object program could not be assembled.; printf "\\a\\a\\a"; echo
      exit 5
   fi
   echo The Usercode is in ${USERCODE}/$name.k3 and the KDF9 executable is in ${BINARY}/$name; echo
   ;;
*)
   ;;
esac
