#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# kids : Compiles and runs a Kidsgrove Algol program
#        calls kalgol to perform compilation
#------------------------------------------------------------------------

if [ -z $KDF9ROOT ]
then
    echo "Please set the KDF9ROOT environment variable to the path of ee9.";
    exit 1;
fi

BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data
WHERE=${KDF9ROOT}/Kidsgrove
SETTINGS=${KDF9ROOT}/settings

${KDF9ROOT}/kalgol $1

if [ -s ${BINARY}/$1 ]
then
   cat ${KDF9ROOT}/settings_2.txt > ${KDF9ROOT}/settings_1.txt
   ${KDF9ROOT}/nine $1 $2 $3 $4
else
   exit 1
fi
