#!/bin/bash

#------------------------------------------------------------------------
# kids : Compiles and runs a Kidsgrove Algol program
#        calls kalgol to perform compilation
#------------------------------------------------------------------------

BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data
WHERE=${KDF9ROOT}/Kidsgrove
SETTINGS=${KDF9ROOT}/settings

trap "rm -f  /tmp/chan6.pt /tmp/ptp.bin /tmp/mt.out /tmp/punch.txt;
      rm -f  ${DATA}/systape.txt ${DATA}/ABS_text.txt;"   \
      0 1 2 3

cat ${SETTINGS}/settings_for_kalgol.txt > ${KDF9ROOT}/settings_1.txt

${KDF9ROOT}/kalgol $1

if [ -s ${BINARY}/$1 ]
then
   cat ${KDF9ROOT}/settings_2.txt > ${KDF9ROOT}/settings_1.txt
   ${KDF9ROOT}/nine $1 $2 $3 $4
else
   exit 1
fi
