#!/bin/sh
rm -f TR1
a60Program=`basename "$1" ".a60"`.a60
w60Program=`basename "$1" ".w60"`.w60
if [ -f "Algol/$w60Program" ]
then
    echo "Converting w60 to a60 format"
    sed -f absconvf.sed Algol/$w60Program > Algol/$a60Program
fi

if [ -f "Algol/$a60Program" ]
then
    cp "Algol/$a60Program" TR1
    exit 0
else
    echo `basename "$0"`: there is no such file as "$a60Program" in the Algol folder!
    exit 1
fi
