#!/bin/sh
BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data

prog=$1
data=$2

if [ x"${prog}"x = xx ]
then
    echo "You have not named a binary program to be run."
    echo
    exit 1
fi

program=`basename "${prog}"`
program=${BINARY}/"$program"
if [ ! -r "$program" ]
then
    echo "The object code file "$program" is absent or unreadable."
    echo
    exit 2
fi

if [ x"${data}"x = xx -o x"${data}"x = x-x ]
then
    >${KDF9ROOT}/TR0
else
    datatxt=${DATA}/`basename "${data}" ".txt"`.txt
    if [ -r "$datatxt" ]
    then
        cat "$datatxt" > ${KDF9ROOT}/TR1
    else
        echo "The file "$datatxt" is absent or unreadable."
        exit 3
    fi
fi

if [ x"$3"x = xx -o x"$3"x = x-x ]
then
    mode=""
else
    mode="-d$3"
fi
if [ x"$4"x = xx -o x"$4"x = x-x ]
then
    miscellany=""
else
    miscellany="-m$4"
fi
if [ x"$5"x = xx -o x"$5"x = x-x ]
then
    TRmode="-TRll"
else
    TRmode="-TR$5"
fi
if [ x"$6"x = xx -o x"$6"x = x-x ]
then
    TPmode="-TPll"
else
    TPmode="-TP$6"
fi
if [ x"$7"x = xx -o x"$7"x = x-x ]
then
    state=""
else
    state="-s$7"
fi

if [ "$mode" = -df ]
then
    time ${KDF9ROOT}/ee9 $state "$mode" "$TRmode" "$TPmode" "$miscellany" +"$program"
else
   ${KDF9ROOT}/ee9 $state "$mode" "$TRmode" "$TPmode" "$miscellany" +"$program"
fi

case $4$8 in
   *z*)
      ;;
   *-*)
      ;;
   *)
    ${KDF9ROOT}/printoutput
esac

