#!/bin/sh

program=`basename "$1" ".kdf9"`.kdf9
if [ ! -f Binary/"$program" ]
then
    echo `basename "$0"`: there is no program named "$program" in the Binary folder!
    exit 1
fi
if /bin/sh ./lud "$2" | grep "data file"
then
    echo
    exit 2
fi

> FW0

mode=-d$3
miscellany=-m$4
if   [ "$mode" = -d ]
then
    ./ee9 -st -df "$miscellany" <Binary/"$program"  >TP0;
elif [ "$3" = - ]
then
    ./ee9 -st -df "$miscellany" <Binary/"$program"  >TP0;
elif [ "$mode" = -df ]
then
    time ./ee9 -st -df "$miscellany" <Binary/"$program"  >TP0;
else
    ./ee9 -st "$mode" "$miscellany"  <Binary/"$program"  >TP0;
fi

   /bin/sh ./printoutput
exit 0
