#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# none : Executes a KDF9 binary with input on TR0 or datafile.
#------------------------------------------------------------------------

if [ -z $KDF9ROOT ]
then
    echo "Please set the KDF9ROOT environment variable to the path of ee9.";
    exit 1;
fi

BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data

prog=$1
data=$2

if [ x"${prog}"x = xx ]
then
   echo "You have not named a binary program to be run."
   echo
   exit 1
fi

program=`basename "${prog}"`
program=${BINARY}/"$program"
if [ ! -r "$program" ]
then
   echo "The object code file "$program" is absent or unreadable."
   echo
   exit 2
fi

if [ x"${data}"x = xx -o x"${data}"x = x-x ]
then
   >${KDF9ROOT}/TR0
else
   datatxt=${DATA}/`basename "${data}" ".txt"`.txt
   if [ -r "$datatxt" ]
   then
      cat "$datatxt" > ${KDF9ROOT}/TR1
   else
      echo "The file "$datatxt" is absent or unreadable."
      exit 3
   fi
fi

if [ x"$3"x = xx -o x"$3"x = x-x ]
then
   mode=""
else
   mode="-d$3"
fi
if [ x"$4"x = xx -o x"$4"x = x-x ]
then
   miscellany=""
else
   miscellany="-m$4"
fi
if [ x"$5"x = xx -o x"$5"x = x-x ]
then
   TRmode="-TRll"
else
   TRmode="-TR$5"
fi
if [ x"$6"x = xx -o x"$6"x = x-x ]
then
   TPmode="-TPll"
else
   TPmode="-TP$6"
fi
if [ x"$7"x = xx -o x"$7"x = x-x ]
then
   state=""
else
   state="-s$7"
fi

if [ "$mode" = -df ]
then
   time ${KDF9ROOT}/ee9 $state "$mode" "$TRmode" -TPkk "$miscellany" +"$program"
else
        ${KDF9ROOT}/ee9 $state "$mode" "$TRmode" -TPkk "$miscellany" +"$program"
fi

${KDF9ROOT}/printoutput
esac
