#!/bin/bash
BINARY=${KDF9_BINARY:-Binary}
DATA=${KDF9_DATA:-Data}

ucc PLT
if [ x$1x = xx ]
then
   >MT1
   cat > ${DATA}/mt_test_labels.txt <<++++
-00-1234WHETLIST|
00000000        |
-00-0552EFPBEAAG|
00000000        |
-00-2339+KOUTPUT/0023004|
0-00-929PRINTEND|
0-00-777AMPEXTM4|
|
++++
   ./nine_test RLT mt_test_labels - zw
   ./nine PLT
   ./mtp MT1
   exit 0
fi
if [ -r ${BINARY}/$1 ]
then
   ./a2b -p2c < ${BINARY}/$1 > ${DATA}/$1-forPLT.txt
   cat ${BINARY}/$1 >> ${DATA}/$1-forPLT.txt
   ./nine PLT $1-forPLT.txt t - lk
   ./mtp MT1
else
   exit 0
fi
