#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# plt : ???
#------------------------------------------------------------------------

if [ -z $KDF9ROOT ]
then
    echo "Please set the KDF9ROOT environment variable to the path of ee9.";
    exit 1;
fi

BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data

${KDF9ROOT}/ucc ${KDF9ROOT}/PLT
if [ x$1x = xx ]
then
   >${KDF9ROOT}/MT1
   cat > ${DATA}/mt_test_labels.txt <<++++
-00-1234WHETLIST|
00000000        |
-00-0552EFPBEAAG|
00000000        |
-00-2339+KOUTPUT/0023004|
0-00-929PRINTEND|
0-00-777AMPEXTM4|
|
++++

   ${KDF9ROOT}/rlt mt_test_labels - zw
   ${KDF9ROOT}/nine PLT
   ${KDF9ROOT}/mtp ${KDF9ROOT}/MT1
   exit 0
fi
if [ -r ${BINARY}/$1 ]
then
   ${KDF9ROOT}/a2b -p2c < ${BINARY}/$1 > ${DATA}/$1-forPLT.txt
   cat ${BINARY}/$1 >> ${DATA}/$1-forPLT.txt
   ${KDF9ROOT}/nine PLT ${DATA}/$1-forPLT.txt t - lk
   ${KDF9ROOT}/mtp ${KDF9ROOT}/MT1
else
   exit 0
fi
