#!/bin/bash
BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data

${KDF9ROOT}/ucc ${KDF9ROOT}/PLT
if [ x$1x = xx ]
then
   >${KDF9ROOT}/MT1
   cat > ${DATA}/mt_test_labels.txt <<++++
-00-1234WHETLIST|
00000000        |
-00-0552EFPBEAAG|
00000000        |
-00-2339+KOUTPUT/0023004|
0-00-929PRINTEND|
0-00-777AMPEXTM4|
|
++++
   ${KDF9ROOT}/nine_test RLT ${DATA}/mt_test_labels - zw
   ${KDF9ROOT}/nine PLT
   ${KDF9ROOT}/mtp ${KDF9ROOT}/MT1
   exit 0
fi
if [ -r ${BINARY}/$1 ]
then
   ${KDF9ROOT}/a2b -p2c < ${BINARY}/$1 > ${DATA}/$1-forPLT.txt
   cat ${BINARY}/$1 >> ${DATA}/$1-forPLT.txt
   ${KDF9ROOT}/nine PLT ${DATA}/$1-forPLT.txt t - lk
   ${KDF9ROOT}/mtp ${KDF9ROOT}/MT1
else
   exit 0
fi
