#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# printoutput : Prints contents of CP0/TP0/TP1/LP0/LP1 to screen.
#------------------------------------------------------------------------

if [ -z $KDF9ROOT ]
then
    echo "Please set the KDF9ROOT environment variable to the path of ee9.";
    exit 1;
fi

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color

if [ -s CP0 ]
then
    echo
    echo -e "${RED} CP0: ${GREEN}===================================================================================${NC}"
    #echo "CP0:"
    #echo "==="
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/CP0) -t UTF8 < ${KDF9ROOT}/CP0 
    cat ${KDF9ROOT}/CP0
    #echo "==="
    echo -e "${GREEN} ========================================================================================${NC}"
fi

if [ -s TP0 ]
then
    echo
    echo -e "${RED} TP0: ${GREEN}===================================================================================${NC}"
    #echo "TP0:"
    #echo "==="
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/TP0) -t UTF8 < ${KDF9ROOT}/TP0 
    #cat ${KDF9ROOT}/TP0    
    #echo "==="
    echo -e "${GREEN} ========================================================================================${NC}"
fi

if [ -s TP1 ]
then
    echo
    echo -e "${RED} TP1: ${GREEN}===================================================================================${NC}"
    #echo "TP1:"
    #echo "==="
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/TP1) -t UTF8 < ${KDF9ROOT}/TP1
    #cat ${KDF9ROOT}/TP1
    #echo "==="
    echo -e "${GREEN} ========================================================================================${NC}"
fi

if [ -s LP0 ]
then
    echo
    echo -e "${RED} LP0: ${GREEN}===================================================================================${NC}"
    #echo "LP0:"
    #echo "==="
    iconv -f $(file -b --mime-encoding ${KDF9ROOT}/LP0) -t UTF8 < ${KDF9ROOT}/LP0 
    #cat ${KDF9ROOT}/LP0
    #echo "==="
    echo -e "${GREEN} ========================================================================================${NC}"
fi

if [ -s LP1 ]
then
    echo
    echo -e "${RED} LP1: ${GREEN}===================================================================================${NC}"
    #echo "LP1:"
    #echo "==="    
    iconv -f $(file -b --mime-encoding ${KDF9ROOT}/LP1) -t UTF8 < ${KDF9ROOT}/LP1 
    #cat ${KDF9ROOT}/LP1
    #echo "==="
    echo -e "${GREEN} ========================================================================================${NC}"
fi