#!/bin/bash

#------------------------------------------------------------------------
# printoutput : Prints contents of CP0/TP0/TP1/LP0/LP1 to screen.
#------------------------------------------------------------------------

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color

if [ -s CP0 ]
then
    echo
    #echo "${RED} CP0: ${GREEN}===================================================================================${NC}"
    echo "CP0:"
    echo "==="
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/CP0) -t UTF8 < ${KDF9ROOT}/CP0 
    cat ${KDF9ROOT}/CP0
    echo "==="
    #echo "${GREEN} ========================================================================================${NC}"
fi

if [ -s TP0 ]
then
    echo
    #echo "${RED} TP0: ${GREEN}===================================================================================${NC}"
    echo "TP0:"
    echo "==="
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/TP0) -t UTF8 < ${KDF9ROOT}/TP0 
    cat ${KDF9ROOT}/TP0    
    #echo "${GREEN} ========================================================================================${NC}"
    echo "==="
fi

if [ -s TP1 ]
then
    echo
    #echo "${RED} TP1: ${GREEN}===================================================================================${NC}"
    echo "TP1:"
    echo "==="
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/TP1) -t UTF8 < ${KDF9ROOT}/TP1
    cat ${KDF9ROOT}/TP1
    echo "==="
    #echo "${GREEN} ========================================================================================${NC}"
fi

if [ -s LP0 ]
then
    echo
    #echo "${RED} LP0: ${GREEN}===================================================================================${NC}"
    echo "LP0:"
    echo "==="
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/LP0) -t UTF8 < ${KDF9ROOT}/LP0 
    cat ${KDF9ROOT}/LP0
    echo "==="
    #echo "${GREEN} ========================================================================================${NC}"
fi

if [ -s LP1 ]
then
    echo
    #echo "${RED} LP1: ${GREEN}===================================================================================${NC}"
    echo "LP1:"
    echo "==="    
    #iconv -f $(file -b --mime-encoding ${KDF9ROOT}/LP1) -t UTF8 < ${KDF9ROOT}/LP1 
    cat ${KDF9ROOT}/LP1
    echo "==="
    #echo "${GREEN} ========================================================================================${NC}"
fi