#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# printoutput : Prints contents of CP0/TP0/TP1/LP0/LP1 to screen.
#------------------------------------------------------------------------

if [ -z $KDF9ROOT ]
then
    echo "Please set the KDF9ROOT environment variable to the path of ee9.";
    exit 1;
fi

trap "rm -f  /tmp/printoutput" 0 1 2 3

TEST=1

function printline {
    echo -e "${RED}$1${GREEN}${BAR}${NC}";
    cat /tmp/printoutput;
    echo -e "${GREEN}${BAR}${NC}";
}

if [ ${TEST} -eq 0 ]
then
    BAR="========================================================================================"
    RED='\033[1;31m'
    GREEN='\033[1;32m'
    NC='\033[0m'  #No Color

    if [ -s CP0 ]
    then
        cat ${KDF9ROOT}/CP0 > /tmp/printoutput;
        printline "CP0:"
    fi

    if [ -s TP0 ]
    then
        cat ${KDF9ROOT}/TP0 > /tmp/printoutput;
        printline "TP0:"
    fi

    if [ -s TP1 ]
    then
        cat ${KDF9ROOT}/TP1 > /tmp/printoutput;
        printline "TP1:"
    fi

    if [ -s LP0 ]
    then
        iconv -f $(file -b --mime-encoding ${KDF9ROOT}/LP0) -t UTF8 < ${KDF9ROOT}/LP0 > /tmp/printoutput;
        printline "LP0:"
    fi

    if [ -s LP1 ]
    then
        iconv -f $(file -b --mime-encoding ${KDF9ROOT}/LP1) -t UTF8 < ${KDF9ROOT}/LP1 > /tmp/printoutput;
        printline "LP1:"
    fi
else
    BAR="==="
    RED=''
    GREEN=''
    NC=''

    if [ -s CP0 ]
    then
        cat ${KDF9ROOT}/CP0 > /tmp/printoutput;
        printline "CP0:\n"
    fi

    if [ -s TP0 ]
    then
        cat ${KDF9ROOT}/TP0 > /tmp/printoutput;
        printline "TP0:\n"
    fi

    if [ -s TP1 ]
    then
        cat ${KDF9ROOT}/TP1 > /tmp/printoutput;
        printline "TP1:\n"
    fi

    if [ -s LP0 ]
    then
        cat ${KDF9ROOT}/LP0 > /tmp/printoutput;
        printline "LP0:\n"
    fi

    if [ -s LP1 ]
    then
        cat ${KDF9ROOT}/LP1 > /tmp/printoutput;
        printline "LP1:\n"
    fi
fi