#!/bin/bash
opt=${1:-ae}

cat >settings_1.txt <<++++
K 14 DR
++++

echo TEST TDRUM - POA, PIA - should end normally:
>DR0; ./ucc TDRUM; ./nine_test TDRUM - t $opt
echo TEST TDRUM - POA, PIA done.
case $1 in
z)
   cat TP0; echo ======; echo
   od -c DR0 | more; echo ======; echo;;
*) ;;
esac

echo TEST TDRUMEOF - POA, PIA - should fail  \"Invalid operand\":
 >DR0; ./ucc TDRUMEOF; ./nine_test TDRUMEOF - t $opt
echo TEST TDRUMEOF - POA, PIA done.
case $1 in
z)
   cat TP0; echo ======; echo
   od -c DR0 | more; echo ======; echo;;
*) ;;
esac

echo TEST TDRUMR2EM - POA, PIB - should end normally:
>DR0; ./ucc TDRUMR2EM; ./nine_test TDRUMR2EM - t $opt
echo TEST  TDRUMR2EM - POA, PIB done.
case $1 in
z)
   cat TP0; echo ======; echo
   od -c DR0 | more; echo ======; echo;;
*) ;;
esac

echo TEST TDRUMW2EM - POB, PIA - should end normally:
>DR0; ./ucc TDRUMW2EM; ./nine_test TDRUMW2EM - t $opt
echo TEST TDRUMW2EM - POB, PIA done.
case $1 in
z)
   cat TP0; echo ======; echo
   od -c DR0 | more; echo ======; echo;;
*) ;;
esac
