#!/bin/bash
SOURCE=${KDF9_USERCODE:-Assembly}
BINARY=${KDF9_BINARY:-Binary}

trap "rm -f kids_test_diff.txt"  \
      0 1 2 3

export KIDSMISC=wz
export KIDSLIST=""
>kids_test.log

./kids FLUID FLUID_data t prh         >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/FLUID.k3     ${BINARY}/FLUID       ${SOURCE}/FLUID-listing.txt
./kids HAAVIE - t prh                 >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/HAAVIE.k3 ${BINARY}/HAAVIE         ${SOURCE}/HAAVIE-listing.txt
./kids HANOI HANOI_data t prh         >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/HANOI.k3     ${BINARY}/HANOI       ${SOURCE}/HANOI-listing.txt
./kids INPUT INPUT_data t prh         >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/INPUT.k3     ${BINARY}/INPUT       ${SOURCE}/INPUT-listing.txt
./kids MANORBOYX - t prh              >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/MANORBOYX.k3 ${BINARY}/MANORBOYX   ${SOURCE}/MANORBOYX-listing.txt
./kids MATMULT - t prh                >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/MATMULT.k3   ${BINARY}/MATMULT     ${SOURCE}/MATMULT-listing.txt
./kids PALSQR - t prh                 >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/PALSQR.k3    ${BINARY}/PALSQR      ${SOURCE}/PALSQR-listing.txt
./kids PENTOMINO PENTOMINO_data t prh >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/PENTOMINO.k3 ${BINARY}/PENTOMINO   ${SOURCE}/PENTOMINO-listing.txt
./kids QSORT - t prh                  >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/QSORT.k3 ${BINARY}/QSORT    ${SOURCE}/QSORT-listing.txt
./kids WHETSTONE - t prh              >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/WHETSTONE.k3 ${BINARY}/WHETSTONE   ${SOURCE}/WHETSTONE-listing.txt
./kids ZELLER ZELLER_data t prh       >>kids_test.log
fgrep "Digital signature of traced orders = " KDF9.log >>kids_test.log;
   rm ${SOURCE}/ZELLER.k3    ${BINARY}/ZELLER      ${SOURCE}/ZELLER-listing.txt

echo
diff kids_test.log kids_good_test.log >kids_test.diff
if [ -s kids_test.diff ]
then
   echo These are the unexpected variances for this run:
   echo ===
   more kids_test.diff
   echo ===
else
   echo These tests ran as expected.
fi
