#!/bin/bash
trap "rm -f whet_test.diff"  \
      0 1 2 3

>whet_test.log

./whet FLUID     t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet GPSPRIMES t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet HAAVIE    t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet HANOI     t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet INPUT     t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet MANORBOYX t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet MATMULT   t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet PENTOMINO t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet WHETSTONE t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log
./whet ZELLER    t prh >>whet_test.log; fgrep "Digital signature" KDF9.log >>whet_test.log

echo
diff whet_test.log whet_good_test.log >whet_test.diff
if [ -s whet_test.diff ]
then
   echo These are the unexpected variances for this run:
   echo ===
   more whet_test.diff
   echo ===
else
   echo These tests ran as expected.
fi
