#!/bin/bash

#------------------------------------------------------------------------
# sttl : ????
#------------------------------------------------------------------------

USERCODE=${KDF9ROOT}/Assembly

trap "rm -f /tmp/STTL.commands /tmp/STTL_tmp"   \
      0 1 2 3

cat >/tmp/STTL.commands <<++++
/^ST *.+ *; *TL *.+ *;/s//ST${2:-7680}; TL${3:-3000};/
++++

if sed -E -f /tmp/STTL.commands ${USERCODE}/$1.k3 > /tmp/STTL_tmp
then
   mv -f /tmp/STTL_tmp ${USERCODE}/$1.k3
else
   echo "**** FAILURE when correcting ST and TL in ${USERCODE}/$1.k3"
fi
