#!/bin/bash

#------------------------------------------------------------------------
# tsp : Runs the KDF9 director.
#------------------------------------------------------------------------

TSD=${KDF9ROOT}/Binary/KKT40E007UPU

cat ${KDF9ROOT}/Settings/FW0_for_Director > ${KDF9ROOT}/FW0

mode=-d$1
miscellany=-m$2

if [ "$mode" = "-d" ]
then
    ${KDF9ROOT}/ee9 -sb -df -TRkk -TPll  +${TSD};
elif [ $mode = -df ]
then
    time ${KDF9ROOT}/ee9 -sb -df -TRkk -TPll  +${TSD};
elif [ $miscellany = -m ]
then
    ${KDF9ROOT}/ee9 -sb "$mode" -TRkk -TPll  +${TSD};
else
    ${KDF9ROOT}/ee9 -sb "$mode" "$miscellany"  -TRkk -TPll +${TSD};
fi

${KDF9ROOT}/printoutput