#!/bin/sh
BINARY=${KDF9ROOT}/Binary
USERCODE=${KDF9ROOT}/Assembly

name=`basename "$1" ".k3"`
if [ -f "${USERCODE}/$name.k3" ]
then
   ${KDF9ROOT}/kal3 -a ${USERCODE}/"$name.k3" > ${USERCODE}/"$name-listing.txt"
   if [ -s a.out ]
   then
      mv -f a.out ${BINARY}/"$name"
   else
      echo ${KDF9ROOT}/kal3 detected error\(s\) in $name.k3
      more "$name-listing.txt"
   fi
   rm -f a.out mt.out
   exit 0
else
   echo `basename "$0"`: there is no file named "$name.k3" in the ${USERCODE} folder!
   echo
   exit 1
fi
