#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# ucc : Compiles a Usercode file to a Binary
#------------------------------------------------------------------------

BINARY=${KDF9ROOT}/Binary
USERCODE=${KDF9ROOT}/Assembly

name=`basename "$1" ".k3"`
if [ -f "${USERCODE}/$name.k3" ]
then
   ${KDF9ROOT}/kal3 -a ${USERCODE}/"$name.k3" > ${USERCODE}/"$name-listing.txt"
   if [ -s a.out ]
   then
      mv -f a.out ${BINARY}/"$name"
   else
      echo "${KDF9ROOT}/kal3 detected error\(s\) in $name.k3"
      more "$name-listing.txt"
   fi
   rm -f a.out mt.out
   exit 0
else
   echo "`basename "$0"`: there is no file named "$name.k3" in the ${USERCODE} folder!"
   echo
   exit 1
fi
