#!/bin/bash

program="$1"
if /bin/sh ./lap "$program"
then
   cp FW0_for_Whetstone FW0

   mode=-d$2
   miscellany=-m$3
   if   [ "$mode" = -d ]
   then
         ./ee9  <Binary/KMW0201--UPU  >TP0;
   elif [ "$mode" = -d- ]
   then
         ./ee9 -sp -df "$miscellany" <Binary/KMW0201--UPU  >TP0;
   elif [ "$mode" = -df ]
   then
      time ./ee9 -sp -df "$miscellany" <Binary/KMW0201--UPU  >TP0;
   else
         ./ee9 -sp "$mode" "$miscellany" <Binary/KMW0201--UPU  >TP0;
   fi

   /bin/sh ./printoutput
else
   exit 1
fi
