#!/bin/bash

#------------------------------------------------------------------------
# whet : Executes a Whetstone Algol program.
#------------------------------------------------------------------------

BINARY=${KDF9ROOT}/Binary
SOURCE=${KDF9ROOT}/Whetstone
FW0FILES=${KDF9ROOT}/FW0Files

if [ x"$1"x = xx ]
then
    echo "You have not named a Whetstone Algol program to be run."
    echo
    exit 1
fi

program=`basename "$1" ".a60"`.a60
program=${SOURCE}/"$program"
if [ -r "$program" ]
then
    cat "$program" > ${KDF9ROOT}/TR1
else
    echo "The source file "$program" is absent or unreadable."
    echo
    exit 2
fi

cat ${FW0FILES}/FW0_for_Whetstone > ${KDF9ROOT}/FW0

mode=-d$2
miscellany=-m$3

if   [ "$mode" = -d ]
then
    ${KDF9ROOT}/ee9 +${BINARY}/KMW0201--UPU;
elif [ "$mode" = -d- ]
then
    ${KDF9ROOT}/ee9 -sp -df "$miscellany" +${BINARY}/KMW0201--UPU;
elif [ "$mode" = -df ]
then
    time ${KDF9ROOT}/ee9 -sp -df "$miscellany" +${BINARY}/KMW0201--UPU;
else
    ${KDF9ROOT}/ee9 -sp "$mode" "$miscellany" +${BINARY}/KMW0201--UPU;
fi

${KDF9ROOT}/printoutput
