#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]; then
    export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests
export TEMPORARY=/tmp

export EE9REGTEST=1

trap "rm -f ${LOGS}/error_output ${TEMPORARY}/ee9_test_case.log" 0 1 2 3

function resetOutputFiles {
    >${KDF9RUNTIME}/CP0
    >${KDF9RUNTIME}/CP1
    >${KDF9RUNTIME}/CR0
    >${KDF9RUNTIME}/CR1
    >${KDF9RUNTIME}/DR0
    >${KDF9RUNTIME}/FD0
    >${KDF9RUNTIME}/FW0
    >${KDF9RUNTIME}/GP0
    >${KDF9RUNTIME}/LP0
    >${KDF9RUNTIME}/LP1
    >${KDF9RUNTIME}/MT0
    >${KDF9RUNTIME}/MT1
    >${KDF9RUNTIME}/MT2
    >${KDF9RUNTIME}/MT3
    >${KDF9RUNTIME}/MT4
    >${KDF9RUNTIME}/MT5
    >${KDF9RUNTIME}/MT6
    >${KDF9RUNTIME}/MT7
    >${KDF9RUNTIME}/SI0
    >${KDF9RUNTIME}/SI1
    >${KDF9RUNTIME}/ST0
    >${KDF9RUNTIME}/ST1
    >${KDF9RUNTIME}/TP0
    >${KDF9RUNTIME}/TP1
    >${KDF9RUNTIME}/TR0
    >${KDF9RUNTIME}/TR1
    >${KDF9RUNTIME}/settings_1.txt
    >${KDF9RUNTIME}/settings_2.txt
}

resetOutputFiles

rm -f ${LOGS}/*

echo
echo
echo "Running CR emulation tests:"
echo "=========================="
echo
${TESTS}/ee9_test_run CR "run_cr_tests" >>${LOGS}/ee9_test_case.log
echo

resetOutputFiles

echo
echo
echo "Running MT emulation tests:"
echo "=========================="
echo
${TESTS}/ee9_test_run MT "run_mt_tests" >>${LOGS}/ee9_test_case.log
echo

resetOutputFiles

echo
echo
echo "Running DR emulation tests:"
echo "=========================="
echo
${TESTS}/ee9_test_run DR "run_dr_tests" >>${LOGS}/ee9_test_case.log
echo

resetOutputFiles

echo
echo
echo "Running FD emulation tests:"
echo "=========================="
echo
${TESTS}/ee9_test_run FD "run_fd_tests" >>${LOGS}/ee9_test_case.log
echo

resetOutputFiles

echo
echo
echo "Running problem program correctness tests:"
echo "========================================="
echo

resetOutputFiles

${TESTS}/ee9_test_case HIG >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case LOG >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case DMP >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case REM >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case DVD >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case ACK >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case HLT >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case HKT >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case MOB >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case GPR >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case FLU >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case WBM >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case RLT >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case TO4 >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case TOX >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case MTW >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case INP >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case WAB n >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case FLO >>${LOGS}/ee9_test_case.log
echo
${TESTS}/ee9_test_case 1DH >>${LOGS}/ee9_test_case.log
echo

echo
echo
echo "Running Kidsgrove kids tests:"
echo "============================================"
echo
${TESTS}/ee9_test_run KAlgol "run_kids_tests ahipr a" >>${LOGS}/ee9_test_case.log
echo

echo
echo
echo Running Kidsgrove wich tests:
echo ============================================
echo
${TESTS}/ee9_test_run WICH "run_wich_tests ahipr a" >>${LOGS}/ee9_test_case.log

diff -diwB --strip-trailing-cr -I 'The Usercode*' -I 'Compilation successful.' ${LOGS}/ee9_test_case.log ${TESTS}/ee9_regr_tests_good.log >${LOGS}/ee9_test_case.diff

if [ ! \( -s ${LOGS}/ee9_test_case.diff \) ]; then
    echo
    echo "Done: ee9 is working as expected."
    echo
    echo "To see the plotted graph, open GP0 with a program that supports"
    echo "Encapsulated PostScript (EPS); e.g. Preview in macOS."
    echo
else
    echo
    echo "The test has shown incorrect results, held in \"${LOGS}/ee9_test_case.log\"."
    echo "The following lists the differences from the qualification test log."
    echo
    more ${LOGS}/ee9_test_case.diff
fi

exit 0
