#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT="$HOME/.kdf9/"
fi



export BINARY=${KDF9ROOT}/Binary
export DATA=${KDF9ROOT}/Data
export KIDSGROVE=${KDF9ROOT}/Kidsgrove
export USERCODE=${KDF9ROOT}/Assembly
export WHETSTONE=${KDF9ROOT}/Whetstone
export LOGS=${KDF9ROOT}/logs
export TESTS=${KDF9ROOT}/tests

export EE9REGTEST=1

trap "rm -f ${LOGS}/error_output"  \
      0 1 2 3

function resetOutputFiles {
> ${KDF9ROOT}/CP0
> ${KDF9ROOT}/CP1
> ${KDF9ROOT}/CR0
> ${KDF9ROOT}/CR1
> ${KDF9ROOT}/DR0
> ${KDF9ROOT}/FD0
> ${KDF9ROOT}/FW0
> ${KDF9ROOT}/GP0
> ${KDF9ROOT}/LP0
> ${KDF9ROOT}/LP1
> ${KDF9ROOT}/MT0
> ${KDF9ROOT}/MT1
> ${KDF9ROOT}/MT2
> ${KDF9ROOT}/MT3
> ${KDF9ROOT}/MT4
> ${KDF9ROOT}/MT5
> ${KDF9ROOT}/MT6
> ${KDF9ROOT}/MT7
> ${KDF9ROOT}/SI0
> ${KDF9ROOT}/SI1
> ${KDF9ROOT}/ST0
> ${KDF9ROOT}/ST1
> ${KDF9ROOT}/TP0
> ${KDF9ROOT}/TP1
> ${KDF9ROOT}/TR0
> ${KDF9ROOT}/TR1
> ${KDF9ROOT}/settings_1.txt
> ${KDF9ROOT}/settings_2.txt
}

resetOutputFiles

rm -f ${LOGS}/*

echo; echo
echo "Running MT emulation tests:"
echo "=========================="
echo
${TESTS}/ee9_test_run MT "run_mt_tests ahipr a"      >> ${LOGS}/ee9_test_case.log; echo

resetOutputFiles

echo; echo
echo "Running FD emulation tests:"
echo "=========================="
echo
${TESTS}/ee9_test_run FD "run_fd_tests ahipr a"      >> ${LOGS}/ee9_test_case.log; echo

resetOutputFiles

echo; echo
echo "Running CR emulation tests:"
echo "=========================="
echo
${TESTS}/ee9_test_run CR "run_cr_tests ahipr a"      >> ${LOGS}/ee9_test_case.log; echo

resetOutputFiles

echo; echo
echo "Running problem program correctness tests:"
echo "=========================="===============
echo

resetOutputFiles

${TESTS}/ee9_test_case HIG $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case LOG $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case DMP $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case ACK $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case HLT $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case HKT $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case MOB $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case GPR $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case FLU $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case WBM $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case RLT $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case TO4 $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case TOX $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case MTW $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case INP $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case HQP $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case WAB n  >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case FLO $1 >> ${LOGS}/ee9_test_case.log; echo
${TESTS}/ee9_test_case 1DH $1 >> ${LOGS}/ee9_test_case.log; echo

diff --color -diwB --strip-trailing-cr -I 'The Usercode*' ${LOGS}/ee9_test_case.log ${TESTS}/ee9_good_test_case.log > ${LOGS}/ee9_test_case.diff

if [ ! \( -s ${LOGS}/ee9_test_case.diff \) ]
then
    echo
    echo "Done: ee9 is working as expected."
    echo
    echo "To see the plotted graph, open GP0 with a program that supports"
    echo "Encapsulated PostScript (EPS); e.g. Preview in macOS."
    echo
else
    echo
    echo "The test has shown incorrect results, held in \"${LOGS}/ee9_test_case.log\"."
    echo "The following lists the differences from the qualification test log."
    echo
    echo "Press RETURN to see the discrepancies:"
    read "reply"
    echo
    more ${LOGS}/ee9_test_case.diff
fi

exit 0
