#!/bin/bash

> ${LOGS}/KDF9.log
testtorun=$(echo "$2" | cut -f1 -d' ')
if [ -f "$testtorun" ]
then
   this_test="$2"
else
   this_test=${TESTS}/"$2"
fi

echo "+++++++++++++++++++ BEGIN  Test Case $1 +++++++++++++++++++"
if /bin/sh $this_test
then
   case x$3x in
   xx)  exit 0
        ;;
   x*x) echo "The signature of this test should be "$3". It was as follows:"
        fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log
        echo "------------------- END OF Test Case $1 -------------------"
        exit 0
        ;;
   esac
else
   echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   echo Test Case "$1": $this_test FAILED!
   echo "------------------- END OF Test Case $1 -------------------"
   exit 1
fi


