#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

mode=ahipr$2
encoding=
case $1 in
1DH) this_test="nine 1DTHFP 1DTHFP_data5"
     signature=\#7671706436245512;;
WAB) this_test="nine GPT GPT_data"
     signature=\#6071426761537263;;
HIG) this_test="nine HiGuys -"
     signature=\#6442100001003204;;
LOG) this_test="nine LOGUYS -"
     signature=\#2012100001003204;;
DMP) this_test="nine DIVA -"
     signature=\#5132117202617243;;
FLO) this_test="nine FLOATT -"
     signature=\#3271342634660173;;
ACK) this_test="nine Ack38 -"
     signature=\#4657410657321314;;
HLT) this_test="nine Leech LEECH_data9"
     signature=\#6151525720423034;;
HKT) this_test="nine Leech LEECH_data9_KDF9"
     encoding=kk
     signature=\#6151525720423034;;
MOB) this_test="whet MANORBOY"
     signature=\#1774104411721111;;
GPR) this_test="whet GPSPRIMES"
     signature=\#3702427170240312;;
FLU) this_test="whet FLUID"
     signature=\#4337171556307416;;
WBM) this_test="whet WHETSTONE"
     signature=\#3226514177100542;;
RLT) this_test="rlt RLT_data"
     signature=\#3506450617016266;;
TO4) this_test="nine OUT4A -"
     signature=\#7017242374042113;;
TOX) this_test="nine OUTX -"
     signature=\#5346716617576440;;
MTW) this_test="whet MTW"
     signature=\#2551007324200157;;
INP) this_test="whet INPUT"
     signature=\#3046175371276175;;
HQP) this_test="kids WEEHAAVIE -"
     export KIDSMISC=w-
     signature=\#4200133757004705;;
*)   echo "test case '$1'\;  UNKNOWN!"
     exit 2;;
esac

rm -f ${USERCODE}/WEEHAAVIE.k3 ${USERCODE}/WEEHAAVIE-listing.txt ${BINARY}/WEEHAAVIE

if ${TESTS}/ee9_test_run "$1" "${KDF9ROOT}/$this_test t $mode $encoding" "$signature"
then
  exit 0
else
  exit 1
fi
