#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

>${LOGS}/KDF9.log

testtorun=$(echo "$2" | cut -f1 -d' ')
if [ -f "${TESTS}/$testtorun" ]
then
   this_test="${TESTS}/$testtorun"
else
   this_test="$2"
fi

echo "+++++++++++++++++++ BEGIN  Test Case $1 +++++++++++++++++++"
if $this_test
then
   case x$3x in
   xx)  exit 0
        ;;
   x*x) echo "The signature of this test should be "$3". It was as follows:"
        fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log
        echo "------------------- END OF Test Case $1 -------------------"
        exit 0
        ;;
   esac
else
   echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   echo Test Case "$1": $this_test FAILED!
   echo "------------------- END OF Test Case $1 -------------------"
   exit 1
fi


