#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

opt=${1:-ae}

cat >settings_1.txt <<++++
K 14 DR
++++

echo "TEST TDRUM - POA, PIA - should end normally:"
>${KDF9ROOT}/DR0; ${KDF9BIN}/ucc TDRUM; ${KDF9BIN}/nine_test TDRUM - t $opt
echo "TEST TDRUM - POA, PIA done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/DR0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDRUMEOF - POA, PIA - should fail  \"Invalid operand\":"
>${KDF9ROOT}/DR0; ${KDF9BIN}/ucc TDRUMEOF; ${KDF9BIN}/nine_test TDRUMEOF - t $opt
echo "TEST TDRUMEOF - POA, PIA done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/DR0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDRUMR2EM - POA, PIB - should end normally:"
>${KDF9ROOT}/DR0; ${KDF9BIN}/ucc TDRUMR2EM; ${KDF9BIN}/nine_test TDRUMR2EM - t $opt
echo "TEST  TDRUMR2EM - POA, PIB done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/DR0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDRUMW2EM - POB, PIA - should end normally:"
>${KDF9ROOT}/DR0; ${KDF9BIN}/ucc TDRUMW2EM; ${KDF9BIN}/nine_test TDRUMW2EM - t $opt
echo "TEST TDRUMW2EM - POB, PIA done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/DR0 | more; echo "======"; echo;;
*) ;;
esac
