#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]
then
    export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests

export EE9REGTEST=1

SOURCE=${KDF9RUNTIME}/Assembly
BINARY=${KDF9RUNTIME}/Binary

trap "rm -f ${LOGS}/kids_test.log ${LOGS}/kids_test_diff.txt" 0 1 2 3

opts="-d=t -m=prh -nc"

>${LOGS}/kids_test.log

kids FLUID FLUID_data $opts         >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/FLUID.k3 ${Binary}/FLUID ${SOURCE}/FLUID-listing.txt

kids HAAVIE $opts                 >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/HAAVIE.k3 ${Binary}/HAAVIE ${SOURCE}/HAAVIE-listing.txt

kids HANOI HANOI_data $opts         >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/HANOI.k3 ${Binary}/HANOI ${SOURCE}/HANOI-listing.txt

kids INPUT INPUT_data $opts         >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/INPUT.k3 ${Binary}/INPUT ${SOURCE}/INPUT-listing.txt

kids MANORBOYX $opts              >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/MANORBOYX.k3 ${Binary}/MANORBOYX ${SOURCE}/MANORBOYX-listing.txt

kids MATMULT $opts                >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/MATMULT.k3   ${Binary}/MATMULT   ${SOURCE}/MATMULT-listing.txt

kids PALSQR $opts                 >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/PALSQR.k3    ${Binary}/PALSQR    ${SOURCE}/PALSQR-listing.txt

kids PENTOMINO PENTOMINO_data $opts >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/PENTOMINO.k3 ${Binary}/PENTOMINO ${SOURCE}/PENTOMINO-listing.txt

kids QSORT $opts                  >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/QSORT.k3 ${Binary}/QSORT  ${SOURCE}/QSORT-listing.txt

kids WHETSTONE $opts              >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/WHETSTONE.k3 ${Binary}/WHETSTONE ${SOURCE}/WHETSTONE-listing.txt

kids ZELLER ZELLER_data $opts       >>${LOGS}/kids_test.log
fgrep "Digital signature of traced orders = " ${LOGS}/KDF9.log >>${LOGS}/kids_test.log;
rm -f ${SOURCE}/ZELLER.k3    ${Binary}/ZELLER    ${SOURCE}/ZELLER-listing.txt

echo
diff -diwB --strip-trailing-cr ${LOGS}/kids_test.log kids_regr_tests_good.log >${LOGS}/kids_test.diff
if [ -s ${LOGS}/kids_test.diff ]
then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/kids_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi
