#!/bin/bash

trap "rm -f si_test_log.txt si_test_diffs.txt; >settings_1.txt" 0 1 2 3

opt=${1:-aenz}
data=${DATA}/SI0_data.txt

cat  > $data <<++++
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@ABCDEFG
HIJKLMNOHIJKLMNO
PQRSTUVWPQRSTUVW
XYZ{}\||XYZ{}\||
@abcdefg@abcdefg
hijklmnohijklmno
pqrstuvwpqrstuvw
xyz    .xyz          |
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@ABCDEFG
HIJKLMNOHIJKLMNO
PQRSTUVWPQRSTUVW
XYZ{}\||XYZ{}\||
@abcdefg@abcdefg
hijklmnohijklmno
pqrstuvwpqrstuvw
xyz    .xyz          |
++++

cat >${KDF9ROOT}/settings_1.txt <<++++
K 15 SI 14 SI
++++

>${LOGS}/si_test_log.txt
>${KDF9ROOT}/SI0
>${KDF9ROOT}/SI1

echo; echo TEST PIB/POB from SI0 to TP:; echo TEST PIB/POB from SI0 to TP: >>${LOGS}/si_test_log.txt
cp $data ${KDF9ROOT}/SI0
${KDF9ROOT}/ucc SI2TP; ${KDF9ROOT}/nine SI2TP - t $opt
cat ${KDF9ROOT}/TP0 >>${LOGS}/si_test_log.txt

echo; echo TEST PIC/POC from SI0 to TP:; echo TEST PIC/POC from SI0 to TP: >>${LOGS}/si_test_log.txt
cp $data ${KDF9ROOT}/SI0
${KDF9ROOT}/ucc SI2TPC; ${KDF9ROOT}/nine SI2TPC - t $opt
cat ${KDF9ROOT}/TP0 >>${LOGS}/si_test_log.txt

echo; echo TEST PIB/POB from TR to SI0:; echo TEST PIB/POB from TR to SI0: >>${LOGS}/si_test_log.txt
>${KDF9ROOT}/SI0
${KDF9ROOT}/ucc TR2SI; ${KDF9ROOT}/nine TR2SI SI0_data t $opt
cat ${KDF9ROOT}/SI0 >>${LOGS}/si_test_log.txt

echo; echo TEST PIC/POC from TR to SI0:; echo TEST PIC/POC from TR to SI0: >>${LOGS}/si_test_log.txt
>${KDF9ROOT}/SI0
${KDF9ROOT}/ucc TR2SIC; ${KDF9ROOT}/nine TR2SIC SI0_data t $opt
cat ${KDF9ROOT}/SI0 >>${LOGS}/si_test_log.txt

echo; echo TEST PIC/POC from TR to SI1:; echo TEST PIC/POC from TR to SI1: >>${LOGS}/si_test_log.txt
>${KDF9ROOT}/SI1
${KDF9ROOT}/ucc TR2SI1C; nine ${KDF9ROOT}/TR2SI1C SI0_data t $opt
cat SI1 >>${LOGS}/si_test_log.txt

echo; echo TEST PIC/POC from SI1 to TP:; echo TEST PIC/POC from SI1 to TP: >>${LOGS}/si_test_log.txt
cp $data ${KDF9ROOT}/SI1
${KDF9ROOT}/ucc SI12TPC; ${KDF9ROOT}/nine SI12TPC - t $opt
cat ${KDF9ROOT}/TP0 >>${LOGS}/si_test_log.txt

echo
diff ${LOGS}/si_test_log.txt ${TESTS}/si_good_test_log.txt >${LOGS}/si_test_diffs.txt
if [ -s ${LOGS}/si_test_diffs.txt ]
then
   echo These are the unexpected variances for this run:
   echo ===
   more ${LOGS}/si_test_diffs.txt
   echo ===
else
   echo These tests ran as expected.
fi
