#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

opt=${1:-ae}

echo "TEST LIV1 - should fail :  jump to 8191"
${KDF9ROOT}/ucc LIV1; ${KDF9ROOT}/nine LIV1 - t $opt
echo "TEST LIV1 done."

echo "TEST LIV2 - should fail :  NOL \< virtual address = 32768"
${KDF9ROOT}/ucc LIV2; ${KDF9ROOT}/nine LIV2 - t $opt
echo "TEST LIV2 done."

echo "TEST LIV3 - should fail : attempt to use unallocated I/O device \#03"
${KDF9ROOT}/ucc LIV3; ${KDF9ROOT}/nine LIV3 - t $opt
echo "TEST LIV3 done."

echo "TEST LIV4 - should fail : 32K-1 \< virtual address = 32768"
${KDF9ROOT}/ucc LIV4; ${KDF9ROOT}/nine LIV4 - t $opt
echo "TEST LIV4 done."

echo "TEST LIV5 - should fail : JCqNZS instruction at syllable 5"
${KDF9ROOT}/ucc LIV5; ${KDF9ROOT}/nine LIV5 - t $opt
echo "TEST LIV5 done."

echo "TEST LIV6 - should fail : invalid SET-type opcode"
${KDF9ROOT}/ucc LIV6; ${KDF9ROOT}/nine LIV6 - t $opt
echo "TEST LIV6 done."

echo "TEST LIV7 - should fail : privileged instruction K7"
${KDF9ROOT}/ucc LIV7; ${KDF9ROOT}/nine LIV7 - t $opt
echo "TEST LIV7 done."

echo "TEST RESET6 - should fail : jump to syllable 6"
${KDF9ROOT}/ucc RESET6; ${KDF9ROOT}/nine RESET6 - t $opt
echo "TEST RESET6 done."

echo "TEST RESET7 - should fail : jump to syllable 7"
${KDF9ROOT}/ucc RESET7; ${KDF9ROOT}/nine RESET7 - t $opt
echo "TEST RESET7 done."
