#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]; then
   export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests
export TEMPORARY=/tmp

export EE9REGTEST=1

#trap "rm -f ${LOGS}/dr_test.log ${LOGS}/dr_test.diff ${KDF9RUNTIME}/settings_1.txt" 0 1 2 3

opt="-d=t -m=ahipr"

cat >${KDF9RUNTIME}/settings_1.txt <<++++
K 14 DR
++++

>${LOGS}/dr_test.log

echo "TEST TDRUM     POA, PIA."
echo "TEST TDRUM     POA, PIA." >>${LOGS}/dr_test.log
>${KDF9RUNTIME}/DR0
ucc TDRUM
nine_test TDRUM $opt >>${LOGS}/dr_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0
   echo "======"
   echo
   od -c ${KDF9RUNTIME}/DR0 | more
   echo "======"
   echo
   ;;
*) ;;
esac

echo "TEST TDRUMR2EM POA, PIB."
echo "TEST TDRUMR2EM POA, PIB." >>${LOGS}/dr_test.log
>${KDF9RUNTIME}/DR0
ucc TDRUMR2EM
nine_test TDRUMR2EM $opt >>${LOGS}/dr_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0
   echo "======"
   echo
   od -c ${KDF9RUNTIME}/DR0 | more
   echo "======"
   echo
   ;;
*) ;;
esac

echo "TEST TDRUMW2EM POB, PIA."
echo "TEST TDRUMW2EM POB, PIA." >>${LOGS}/dr_test.log
>${KDF9RUNTIME}/DR0
ucc TDRUMW2EM
nine_test TDRUMW2EM $opt >>${LOGS}/dr_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0
   echo "======"
   echo
   od -c ${KDF9RUNTIME}/DR0 | more
   echo "======"
   echo
   ;;
*) ;;
esac

echo "TEST TDROUTS   11, 12, 13, 14."
echo "TEST TDROUTS   11, 12, 13, 14." >>${LOGS}/dr_test.log
>${KDF9RUNTIME}/DR0
ucc TDROUTS
nine_test TDROUTS ${opt}k
fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log

echo "TEST TDROUTFAILS   13."
echo "TEST TDROUTFAILS   13." >>${LOGS}/dr_test.log
>${KDF9RUNTIME}/DR0
ucc TDROUTFAILS
VARIABLE=3 nine_test TDROUTFAILS ${opt}k
fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log

echo "TEST TDROUTFAILS   11, 13."
echo "TEST TDROUTFAILS   11, 13." >>${LOGS}/dr_test.log
>${KDF9RUNTIME}/DR0
ucc TDROUTFAILS
VARIABLE=6 nine_test TDROUTFAILS ${opt}k
fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log

echo
diff -diwB --strip-trailing-cr ${LOGS}/dr_test.log ${TESTS}/dr_regr_tests_good.log >${LOGS}/dr_test.diff
if [ -s ${LOGS}/dr_test.diff ]; then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/dr_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi
