#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]; then
    export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests
export TEMPORARY=/tmp

export EE9REGTEST=1

opt="-d=t -m=ahipr"

echo "TEST NOUV0 - REV should end normally, as the NEST depth is constant"
ucc NOUV0
nine NOUV0 $opt
echo "TEST NOUV0 done."

echo "TEST NOUV1 - should fail: NEST lacks 1 operand for ERASE."
ucc NOUV1
nine NOUV1 $opt
echo "TEST NOUV1 done."

echo "TEST NOUV2 - should fail: NEST too full for 2 operands of DUPD."
ucc NOUV2
nine NOUV2 $opt
echo "TEST NOUV2 done."

echo "TEST NOUV3 - should fail: empty SJNS for LINK."
ucc NOUV3
nine NOUV3 $opt
echo "TEST NOUV3 done."

echo "TEST NOUV4 - should fail: full SJNS for =LINK."
ucc NOUV4
nine NOUV4 $opt
echo "TEST NOUV4 done."

echo "TEST NOUV5 - should fail: NEST lacks 1 operand for Jr=."
ucc NOUV5
nine NOUV5 $opt
echo "TEST NOUV5 done."

echo "TEST NOUV6 - should fail: empty NEST for Jr=Z."
ucc NOUV6
nine NOUV6 $opt
echo "TEST NOUV6 done."

echo "TEST NOUV7 - should fail: empty SJNS for EXIT."
ucc NOUV7
nine NOUV7 $opt
echo "TEST NOUV7 done."

echo "TEST NOUV8 - should fail: full SJNS for JSr."
ucc NOUV8
nine NOUV8 $opt
echo "TEST NOUV8 done."

echo "TEST NOUV9 - should fail: NEST lacks 3 operands for +D."
ucc NOUV9
nine NOUV9 $opt
echo "TEST NOUV9 done."
