#!/bin/bash
trap "rm -f ${LOGS}/whet_test.diff ${LOGS}/whet_test.log"  \
      0 1 2 3

>${LOGS}/whet_test.log

${KDF9ROOT}/whet FLUID     t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet GPSPRIMES t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet HAAVIE    t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet HANOI     t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet INPUT     t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet MANORBOYX t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet MATMULT   t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet PENTOMINO t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet WHETSTONE t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log
${KDF9ROOT}/whet ZELLER    t prh >>${LOGS}/whet_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/whet_test.log

echo
diff ${LOGS}/whet_test.log ${TESTS}/whet_good_test.log >${LOGS}/whet_test.diff
if [ -s ${LOGS}/whet_test.diff ]
then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/whet_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi
