#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

trap "rm -f ${KDF9RUNTIME}/MTx ${DATA}/mt_test_labels.txt ${LOGS}/mt_test.log ${LOGS}/mt_test.diff"  0 1 2 3

opt=${1:-ahpr}

>${KDF9RUNTIME}/MT0
>${KDF9RUNTIME}/MT1
>${KDF9RUNTIME}/MT2
>${KDF9RUNTIME}/MT3
>${KDF9RUNTIME}/MT4
>${KDF9RUNTIME}/MT5
>${KDF9RUNTIME}/ST0

cat > ${DATA}/mt_test_labels.txt <<++++
-00-1234WHETLIST|
00000000        |
-00-0552EFPBEAAG|
77777777MS-DUMP.|
-00-2339+KOUTPUT/0023004|
0-00-929PRINTEND|
0-00-777AMPEXTM4|
|
++++

${KDF9BIN}/rlt mt_test_labels - zw

cat ${KDF9RUNTIME}/MT2 > ${KDF9RUNTIME}/MTx

> ${KDF9RUNTIME}/MT1
> ${LOGS}/mt_test.log

echo "TEST A - MRWD, MFR, MBR, MLW, MBSK, MLB, MFSK, MGAP, writing max block, MWIPE - should terminate normally:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4A; ${KDF9BIN}/nine OUT4A - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST B - GAP in unWIPEd area - should fail \"Invalid operand\":"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4B; ${KDF9BIN}/nine OUT4B - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST C - valid WIPE at end of data - should end normally:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4C; ${KDF9BIN}/nine OUT4C - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST D - reading past the end of data - should fail \"Invalid operand\":"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4D; ${KDF9BIN}/nine OUT4D - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST E - attempt to write past PET - should fail \"Invalid operand\":"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4E; ${KDF9BIN}/nine OUT4E - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST F - MW, MWE, MFRE and MBRE - should end normally:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4F; ${KDF9BIN}/nine OUT4F - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST G - WIPE entire tape, leaving it unlabelled - should end normally:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4G; ${KDF9BIN}/nine OUT4G - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST H - writing to ETW - should end normally:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4H; ${KDF9BIN}/nine OUT4H - t $opt >>${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST I - MBR at BTW - should LIV:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4I; ${KDF9BIN}/nine OUT4I - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST J - MBSK at BTW - should LIV:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4J; ${KDF9BIN}/nine OUT4J - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST K - MBR after label block, R/W 1-word blocks - should end normally:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4K; ${KDF9BIN}/nine OUT4K - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac
echo "TEST L - R/W 32K-word blocks - should end normally:"
cat ${KDF9RUNTIME}/MTx > ${KDF9RUNTIME}/MT2; ${KDF9BIN}/ucc OUT4L; ${KDF9BIN}/nine OUT4L - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log

case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac

echo "TEST T - like TEST A but for 7-track decks - should end normally:"
${KDF9BIN}/rlt mt_test_labels - zw; ${KDF9BIN}/ucc OUT4T; ${KDF9BIN}/nine OUT4T - t $opt >> ${LOGS}/mt_test.log; fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/mt_test.log
case $opt in
   z)
      echo "======"; cat ${KDF9RUNTIME}/TP0; echo "======"; echo;;
   *) ;;
esac

echo
diff -diwB --strip-trailing-cr ${LOGS}/mt_test.log ${TESTS}/mt_good_test.log >${LOGS}/mt_test.diff
if [ -s mt_test.diff ]
then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/mt_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi


