#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

trap "rm -f ${LOGS}/si_test.log ${LOGS}/si_test_diffs.txt; >settings_1.txt" 0 1 2 3

opt=${1:-aenz}
data=${DATA}/SI0_data.txt

cat  > $data <<++++
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@ABCDEFG
HIJKLMNOHIJKLMNO
PQRSTUVWPQRSTUVW
XYZ{}\||XYZ{}\||
@abcdefg@abcdefg
hijklmnohijklmno
pqrstuvwpqrstuvw
xyz    .xyz          |
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@ABCDEFG
HIJKLMNOHIJKLMNO
PQRSTUVWPQRSTUVW
XYZ{}\||XYZ{}\||
@abcdefg@abcdefg
hijklmnohijklmno
pqrstuvwpqrstuvw
xyz    .xyz          |
++++

cat >${KDF9RUNTIME}/settings_1.txt <<++++
K 15 SI 14 SI
++++

>${LOGS}/si_test.log
>${KDF9RUNTIME}/SI0
>${KDF9RUNTIME}/SI1

echo; echo "TEST PIB/POB from SI0 to TP:; echo TEST PIB/POB from SI0 to TP:" >>${LOGS}/si_test.log
cat $data > ${KDF9RUNTIME}/SI0
ucc SI2TP; nine SI2TP - t $opt
cat ${KDF9RUNTIME}/TP0 >>${LOGS}/si_test.log

echo; echo "TEST PIC/POC from SI0 to TP:; echo TEST PIC/POC from SI0 to TP:" >>${LOGS}/si_test.log
cat $data > ${KDF9RUNTIME}/SI0
ucc SI2TPC; nine SI2TPC - t $opt
cat ${KDF9RUNTIME}/TP0 >>${LOGS}/si_test.log

echo; echo "TEST PIB/POB from TR to SI0:; echo TEST PIB/POB from TR to SI0:" >>${LOGS}/si_test.log
>${KDF9RUNTIME}/SI0
ucc TR2SI; nine TR2SI SI0_data t $opt
cat ${KDF9RUNTIME}/SI0 >>${LOGS}/si_test.log

echo; echo "TEST PIC/POC from TR to SI0:; echo TEST PIC/POC from TR to SI0:" >>${LOGS}/si_test.log
>${KDF9RUNTIME}/SI0
ucc TR2SIC; nine TR2SIC SI0_data t $opt
cat ${KDF9RUNTIME}/SI0 >>${LOGS}/si_test.log

echo; echo "TEST PIC/POC from TR to SI1:; echo TEST PIC/POC from TR to SI1:" >>${LOGS}/si_test.log
>${KDF9RUNTIME}/SI1
ucc TR2SI1C; nine ${KDF9RUNTIME}/TR2SI1C SI0_data t $opt
cat SI1 >>${LOGS}/si_test.log

echo; echo "TEST PIC/POC from SI1 to TP:; echo TEST PIC/POC from SI1 to TP:" >>${LOGS}/si_test.log
cat $data > ${KDF9RUNTIME}/SI1
ucc SI12TPC; nine SI12TPC - t $opt
cat ${KDF9RUNTIME}/TP0 >>${LOGS}/si_test.log

echo
diff -diwB --strip-trailing-cr ${LOGS}/si_test.log ${TESTS}/si_good_test.log >${LOGS}/si_test.diff
if [ -s ${LOGS}/si_test_diffs.txt ]
then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/si_test_diffs.txt
   echo "==="
else
   echo "These tests ran as expected."
fi
