#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]
then
    export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests

export EE9REGTEST=1

trap "rm -f ${LOGS}/fd_test.log ${LOGS}/fd_test.diff ${KDF9RUNTIME}/settings_1.txt" 0 1 2 3

opt="-d=t -m=ahipr"

cat >${KDF9RUNTIME}/settings_1.txt <<++++
K 14 FD
++++

> ${LOGS}/fd_test.log

echo "TEST TDISC     POA, PIA, PMA, PMF."
echo "TEST TDISC     POA, PIA, PMA, PMF." >> ${LOGS}/fd_test.log
>${KDF9RUNTIME}/FD0; ucc TDISC; nine_test TDISC $opt >> ${LOGS}/fd_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >> ${LOGS}/fd_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISCOR   POA, PIA, PMA, PMF."
echo "TEST TDISCOR   POA, PIA, PMA, PMF." >> ${LOGS}/fd_test.log
 >${KDF9RUNTIME}/FD0; ucc TDISCOR; nine_test TDISCOR $opt >> ${LOGS}/fd_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >> ${LOGS}/fd_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISCEM   POB, PIA, PMA."
echo "TEST TDISCEM   POB, PIA, PMA." >> ${LOGS}/fd_test.log
>${KDF9RUNTIME}/FD0; ucc TDISCEM; nine_test TDISCEM $opt >> ${LOGS}/fd_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >> ${LOGS}/fd_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISCFH   POC, PIC done."
echo "TEST TDISCFH   POC, PIC done." >> ${LOGS}/fd_test.log
>${KDF9RUNTIME}/FD0; ucc TDISCFH; nine_test TDISCFH $opt >> ${LOGS}/fd_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >> ${LOGS}/fd_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISCFHNS POC, POK, PIC, PIG."
echo "TEST TDISCFHNS POC, POK, PIC, PIG." >> ${LOGS}/fd_test.log
>${KDF9RUNTIME}/FD0; ucc TDISCFHNS; nine_test TDISCFHNS $opt >> ${LOGS}/fd_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >> ${LOGS}/fd_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TFDOUTS 41, 42, 43, 44, 45."
echo "TEST TFDOUTS 41, 42, 43, 44, 45." >> ${LOGS}/fd_test.log
>${KDF9RUNTIME}/FD0; ucc TFDOUTS; nine_test TFDOUTS $opt >> ${LOGS}/fd_test.log
fgrep "Digital signature" ${LOGS}/KDF9.log >> ${LOGS}/fd_test.log
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo
diff -diwB --strip-trailing-cr ${LOGS}/fd_test.log ${TESTS}/fd_regr_tests_good.log > ${LOGS}/fd_test.diff
if [ -s ${LOGS}/fd_test.diff ]
then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/fd_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi
