#!/bin/bash
opt=${1:-ae}

cat >${KDF9ROOT}/settings_1.txt <<++++
K 14 FD
++++

echo "TEST TDISK - POA, PIA, PMA, PMF - should end normally:"
>${KDF9ROOT}/FD0; ${KDF9ROOT}/ucc TDISK; ${KDF9ROOT}/nine_test TDISK - t $opt
echo "TEST TDISK - POA, PIA, PMA, PMF done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKOR - POA, PIA, PMA, PMF - should end normally:"
 >${KDF9ROOT}/FD0; ${KDF9ROOT}/ucc TDISKOR; ${KDF9ROOT}/nine_test TDISKOR - t $opt
echo "TEST TDISKOR - POA, PIA, PMA, PMF done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKEM - POB, PIA, PMA - should end normally:"
>${KDF9ROOT}/FD0; ${KDF9ROOT}/ucc TDISKEM; ${KDF9ROOT}/nine_test TDISKEM - t $opt
echo "TEST TDISKEM - POB, PIA, PMA done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKFH - POC, PIC - should end normally:"
>${KDF9ROOT}/FD0; ${KDF9ROOT}/ucc TDISKFH; ${KDF9ROOT}/nine_test TDISKFH - t $opt
echo "TEST TDISKFH - POC, PIC done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKFHNS - POC, POK, PIC, PIG - should end normally:"
>${KDF9ROOT}/FD0; ${KDF9ROOT}/ucc TDISKFHNS; ${KDF9ROOT}/nine_test TDISKFHNS - t $opt
echo "TEST TDISKFHNS - POC, POK, PIC, PIG done."
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo "======"; echo
   od -c ${KDF9ROOT}/FD0 | more; echo "======"; echo;;
*) ;;
esac
