#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

trap "rm -f ${DATA}/crtest_data.txt ${LOGS}/cr_test.log ${LOGS}/cr_test.diff" 0 1 2 3
opt=${1:-ae}

data=${DATA}/crtest_data.txt

cat  > $data <<++++
" ®©¬#%'................................................................COLUMN80________________________________________________________________________COL. 160
:=()£*,/:=()£*,/
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@abcdefg
HIJKLMNOhijklmno
PQRSTUVWpqrstuvw
XYZ{}|\Øxyz{}|\Ø
        .
" ®©¬#%'................................................................COLUMN80________________________________________________________________________COL. 160
:=()£*,/:=()£*,/
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@abcdefg
HIJKLMNOhijklmno
PQRSTUVWpqrstuvw
XYZ{}|\Øxyz{}|\Ø
        .
++++

echo "The following tests use this data:"
echo "===="
cat $data
echo "===="
cat <<++++

The output to CP0 should look like this:
=====
" ®©¬#%'................................................................COLUMN80________________________________________________________________________COL. 160
:=()£*,/:=()£*,/
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@ABCDEFG
HIJKLMNOHIJKLMNO
PQRSTUVWPQRSTUVW
XYZ{}|\ØXYZ{}|\Ø
        .
" ®©¬#%'................................................................COLUMN80________________________________________________________________________COL. 160
:=()£*,/:=()£*,/
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@ABCDEFG
HIJKLMNOHIJKLMNO
PQRSTUVWPQRSTUVW
XYZ{}|
        .
=====
the penultimate input line:
XYZ{}|\Øxyz{}|\Ø
should be punched out like this:
XYZ{}|
because the second set of 8 lines is read/punched to EM.
An alphanumeric read/write omits everything after "COLUMN80".
___________________________________________________________


++++

> ${LOGS}/cr_test.log

echo "TEST PIA PIB - POA 160-column binary write:"
${KDF9BIN}/ucc CRTAB; ${KDF9BIN}/crnine CRTAB crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo "TEST PIC PID - POC 160-column character binary write:"
${KDF9BIN}/ucc CRTCD; ${KDF9BIN}/crnine CRTCD crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo "TEST PIE PIF - POG 80-column alphanumeric write:"
${KDF9BIN}/ucc CRTEF; ${KDF9BIN}/crnine CRTEF crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo "TEST PIG PIH - POL 80-column alphanumeric character-per-word write:"
${KDF9BIN}/ucc CRTGH; ${KDF9BIN}/crnine CRTGH crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo "TEST POA POB - PIA 160-column binary read:"
${KDF9BIN}/ucc CPTAB; ${KDF9BIN}/crnine CPTAB crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo "TEST POC POD - PIC 160-column character binary read:"
${KDF9BIN}/ucc CPTCD; ${KDF9BIN}/crnine CPTCD crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo "TEST POG POH - PIE 80-column alphanumeric read:"
${KDF9BIN}/ucc CPTGH; ${KDF9BIN}/crnine CPTGH crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo "TEST POL POK (sic) - PIG 80-column alphanumeric character-per-word read:"
${KDF9BIN}/ucc CPTKL; ${KDF9BIN}/crnine CPTKL crtest_data t $opt >> ${LOGS}/cr_test.log
case $opt in
z)
   echo "===="; cat CP0; echo "===="; echo;;
*) ;;
esac

echo
diff -diwB --strip-trailing-cr ${LOGS}/cr_test.log ${TESTS}/cr_good_test.log > ${LOGS}/cr_test.diff
if [ -s ${LOGS}/cr_test.diff ]
then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/cr_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi
