#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]; then
   export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests
export TEMPORARY=/tmp

export EE9REGTEST=1

#trap "rm -f ${LOGS}/walgol_test.diff ${LOGS}/walgol_test.log ${TEMPORARY}/walgoloutput" 0 1 2 3

function runtest() {
   walgol $1 -d=t -m=prh >>${LOGS}/walgol_test.log
   fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/walgol_test.log
   echo $1 DONE >>${LOGS}/walgol_test.log
}

>${LOGS}/walgol_test.log

runtest FLUID
runtest GPSPRIMES
runtest HANOI
runtest INPUT
runtest MANORBOY
runtest MATMULT
runtest PENTOMINO
runtest WEEHAAVIE
runtest WHETSTONE
runtest ZELLER

echo
iconv -f $(file -b --mime-encoding ${LOGS}/walgol_test.log) -t UTF8 <${LOGS}/walgol_test.log >${TEMPORARY}/whetoutput
cat ${TEMPORARY}/whetoutput >${LOGS}/walgol_test.log
diff -diwB --strip-trailing-cr ${LOGS}/walgol_test.log ${TESTS}/whet_regr_tests_good.log >${LOGS}/walgol_test.diff
if [ -s ${LOGS}/walgol_test.diff ]; then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/walgol_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi
