#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]; then
   export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests
export TEMPORARY=/tmp

export EE9REGTEST=1

#trap "rm -f ${DATA}/crtest_data.txt ${LOGS}/cr_test.log ${LOGS}/cr_test.diff ${TEMPORARY}/cr_test.log" 0 1 2 3

opt="-d=t -m=ae"

crdata=${DATA}/crtest_data.txt

cat >$crdata <<++++
" ®©¬#%'................................................................COLUMN80________________________________________________________________________COL. 160
:=()£*,/:=()£*,/
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@abcdefg
HIJKLMNOhijklmno
PQRSTUVWpqrstuvw
XYZ{}|\Øxyz{}|\Ø
        .
" ®©¬#%'................................................................COLUMN80________________________________________________________________________COL. 160
:=()£*,/:=()£*,/
0123456701234567
89_º;+-.89_º;+-.
@ABCDEFG@abcdefg
HIJKLMNOhijklmno
PQRSTUVWpqrstuvw
XYZ{}|\Øxyz{}|\Ø
        .
++++

>${LOGS}/cr_test.log

echo "TEST PIA PIB - POA 160-column binary write:"
ucc CRTAB
crnine CRTAB crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo "TEST PIC PID - POC 160-column character binary write:"
ucc CRTCD
crnine CRTCD crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo "TEST PIE PIF - POG 80-column alphanumeric write:"
ucc CRTEF
crnine CRTEF crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo "TEST PIG PIH - POL 80-column alphanumeric character-per-word write:"
ucc CRTGH
crnine CRTGH crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo "TEST POA POB - PIA 160-column binary read:"
ucc CPTAB
crnine CPTAB crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo "TEST POC POD - PIC 160-column character binary read:"
ucc CPTCD
crnine CPTCD crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo "TEST POG POH - PIE 80-column alphanumeric read:"
ucc CPTGH
crnine CPTGH crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo "TEST POL POK (sic) - PIG 80-column alphanumeric character-per-word read:"
ucc CPTKL
crnine CPTKL crtest_data $opt >>${LOGS}/cr_test.log
case $opt in
z)
   echo "===="
   cat CP0
   echo "===="
   echo
   ;;
*) ;;
esac

echo
iconv -f $(file -b --mime-encoding ${LOGS}/cr_test.log) -t UTF8 <${LOGS}/cr_test.log >${TEMPORARY}/cr_test.log
cat ${TEMPORARY}/cr_test.log >${LOGS}/cr_test.log
diff -diwB --strip-trailing-cr ${LOGS}/cr_test.log ${TESTS}/cr_regr_tests_good.log >${LOGS}/cr_test.diff
if [ -s ${LOGS}/cr_test.diff ]; then
   echo "These are the unexpected variances for this run:"
   echo "==="
   more ${LOGS}/cr_test.diff
   echo "==="
else
   echo "These tests ran as expected."
fi
