#!/bin/bash
opt=${1:-ae}

cat >settings_1.txt <<++++
K 14 DR
++++

echo TEST TDRUM - POA, PIA - should end normally:
>${KDF9ROOT}/DR0; ${KDF9ROOT}/ucc TDRUM; ${KDF9ROOT}/nine_test TDRUM - t $opt
echo TEST TDRUM - POA, PIA done.
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo ======; echo
   od -c ${KDF9ROOT}/DR0 | more; echo ======; echo;;
*) ;;
esac

echo TEST TDRUMEOF - POA, PIA - should fail  \"Invalid operand\":
>${KDF9ROOT}/DR0; ${KDF9ROOT}/ucc TDRUMEOF; ${KDF9ROOT}/nine_test TDRUMEOF - t $opt
echo TEST TDRUMEOF - POA, PIA done.
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo ======; echo
   od -c ${KDF9ROOT}/DR0 | more; echo ======; echo;;
*) ;;
esac

echo TEST TDRUMR2EM - POA, PIB - should end normally:
>${KDF9ROOT}/DR0; ${KDF9ROOT}/ucc TDRUMR2EM; ${KDF9ROOT}/nine_test TDRUMR2EM - t $opt
echo TEST  TDRUMR2EM - POA, PIB done.
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo ======; echo
   od -c ${KDF9ROOT}/DR0 | more; echo ======; echo;;
*) ;;
esac

echo TEST TDRUMW2EM - POB, PIA - should end normally:
>${KDF9ROOT}/DR0; ${KDF9ROOT}/ucc TDRUMW2EM; ${KDF9ROOT}/nine_test TDRUMW2EM - t $opt
echo TEST TDRUMW2EM - POB, PIA done.
case $1 in
z)
   cat ${KDF9ROOT}/TP0; echo ======; echo
   od -c ${KDF9ROOT}/DR0 | more; echo ======; echo;;
*) ;;
esac
