#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

opt=${1:-ae}

echo "TEST NOUV0 - REV should end normally, as the NEST depth is constant"
${KDF9ROOT}/ucc NOUV0; ${KDF9ROOT}/nine NOUV0 - t $opt
echo "TEST NOUV0 done."

echo "TEST NOUV1 - ERASE empty NEST"
${KDF9ROOT}/ucc NOUV1; ${KDF9ROOT}/nine NOUV1 - t $opt
echo "TEST NOUV1 done."

echo "TEST NOUV2 - DUPD overfills NEST"
${KDF9ROOT}/ucc NOUV2; ${KDF9ROOT}/nine NOUV2 - t $opt
echo "TEST NOUV2 done."

echo "TEST NOUV3 - LINK with empty SJNS"
${KDF9ROOT}/ucc NOUV3; ${KDF9ROOT}/nine NOUV3 - t $opt
echo "TEST NOUV3 done."

echo "TEST NOUV4 - =LINK loop overfills SJNS"
${KDF9ROOT}/ucc NOUV4; ${KDF9ROOT}/nine NOUV4 - t $opt
echo "TEST NOUV4 done."

echo "TEST NOUV5 - Jr= with 1 word in NEST"
${KDF9ROOT}/ucc NOUV5; ${KDF9ROOT}/nine NOUV5 - t $opt
echo "TEST NOUV5 done."

echo "TEST NOUV6 - Jr=Z with empty NEST"
${KDF9ROOT}/ucc NOUV6; ${KDF9ROOT}/nine NOUV6 - t $opt
echo "TEST NOUV6 done."

echo "TEST NOUV7 - EXIT with empty SJNS"
${KDF9ROOT}/ucc NOUV7; ${KDF9ROOT}/nine NOUV7 - t $opt
echo "TEST NOUV7 done."

echo "TEST NOUV8 - JSr loop overfills SJNS"
${KDF9ROOT}/ucc NOUV8; ${KDF9ROOT}/nine NOUV8 - t $opt
echo "TEST NOUV8 done."

echo "TEST NOUV9 - +D with only 1 word in NEST"
${KDF9ROOT}/ucc NOUV9; ${KDF9ROOT}/nine NOUV9 - t $opt
echo "TEST NOUV9 done.""
