#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------

opt=${1:-ae}

cat >${KDF9RUNTIME}/settings_1.txt <<++++
K 14 FD
++++

echo "TEST TDISK - POA, PIA, PMA, PMF - should end normally:"
>${KDF9RUNTIME}/FD0; ucc TDISK; nine_test TDISK - t $opt
echo "TEST TDISK - POA, PIA, PMA, PMF done."
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKOR - POA, PIA, PMA, PMF - should end normally:"
 >${KDF9RUNTIME}/FD0; ucc TDISKOR; nine_test TDISKOR - t $opt
echo "TEST TDISKOR - POA, PIA, PMA, PMF done."
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKEM - POB, PIA, PMA - should end normally:"
>${KDF9RUNTIME}/FD0; ucc TDISKEM; nine_test TDISKEM - t $opt
echo "TEST TDISKEM - POB, PIA, PMA done."
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKFH - POC, PIC - should end normally:"
>${KDF9RUNTIME}/FD0; ucc TDISKFH; nine_test TDISKFH - t $opt
echo "TEST TDISKFH - POC, PIC done."
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac

echo "TEST TDISKFHNS - POC, POK, PIC, PIG - should end normally:"
>${KDF9RUNTIME}/FD0; ucc TDISKFHNS; nine_test TDISKFHNS - t $opt
echo "TEST TDISKFHNS - POC, POK, PIC, PIG done."
case $1 in
z)
   cat ${KDF9RUNTIME}/TP0; echo "======"; echo
   od -c ${KDF9RUNTIME}/FD0 | more; echo "======"; echo;;
*) ;;
esac
