#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]; then
    export KDF9RUNTIME="$HOME/.kdf9"
fi

export DATA=${KDF9RUNTIME}/Data
export KIDSGROVE=${KDF9RUNTIME}/Kidsgrove
export USERCODE=${KDF9RUNTIME}/Assembly
export WHETSTONE=${KDF9RUNTIME}/Whetstone
export LOGS=${KDF9RUNTIME}/logs
export TESTS=${KDF9RUNTIME}/tests

export EE9REGTEST=1

#trap "rm -f ${LOGS}/liv_test.log ${LOGS}/liv_test.diff" 0 1 2 3

opt="-d=t -m=ahipr"

echo "TEST LIV1 - should fail :  jump to 8191"
ucc LIV1
nine LIV1 $opt >>${LOGS}/liv_test.log
echo "TEST LIV1 done."

echo "TEST LIV2 - should fail :  NOL \< virtual address = 32768"
ucc LIV2
nine LIV2 $opt >>${LOGS}/liv_test.log
echo "TEST LIV2 done."

echo "TEST LIV3 - should fail : attempt to use unallocated I/O device \#03"
ucc LIV3
nine LIV3 $opt >>${LOGS}/liv_test.log
echo "TEST LIV3 done."

echo "TEST LIV4 - should fail : 32K-1 \< virtual address = 32768"
ucc LIV4
nine LIV4 $opt >>${LOGS}/liv_test.log
echo "TEST LIV4 done."

echo "TEST LIV5 - should fail : JCqNZS instruction at syllable 5"
ucc LIV5
nine LIV5 $opt >>${LOGS}/liv_test.log
echo "TEST LIV5 done."

echo "TEST LIV6 - should fail : invalid SET-type opcode"
ucc LIV6
nine LIV6 $opt >>${LOGS}/liv_test.log
echo "TEST LIV6 done."

echo "TEST LIV7 - should fail : privileged instruction K7"
ucc LIV7
nine LIV7 $opt >>${LOGS}/liv_test.log
echo "TEST LIV7 done."

echo "TEST RESET6 - should fail : jump to syllable 6"
ucc RESET6
nine RESET6 $opt >>${LOGS}/liv_test.log
echo "TEST RESET6 done."

echo "TEST RESET7 - should fail : jump to syllable 7"
ucc RESET7
nine RESET7 $opt >>${LOGS}/liv_test.log
echo "TEST RESET7 done."
