PROGRAM TEST1 (OUTPUT);
TYPE
   ADDRESS = INTEGER;
VAR
   INT1, INT2, INT3, INT4, INT5, INT6 : -2000..+2000;
   CHAR1, CHAR2, CHAR3, CHAR4 : 'A'..'Z';
   BOOL1A, BOOL1B : FALSE..FALSE;
   BOOL2A, BOOL2B : TRUE..TRUE;
   BOOL3 : FALSE..TRUE;
   DAY1, DAY2, DAY3 : (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY);
   WEEK1, WEEK2, WEEK3A, WEEK3B : MONDAY..FRIDAY;
   PTRTOINT : ^ INTEGER;
   PTRTOCHAR : ^ CHAR;
   PTRTOBOOL : ^ BOOLEAN;

   PROCEDURE INVALIDATE (A : ADDRESS);
      BEGIN
      STOREWORDAT(-MAXINT, A);
      STOREWORDAT(WORDAT(A)-1, A);
      END (*INVALIDATE*);

BEGIN (* TEST1 *)
STOREWORDAT(-MAXINT, ADDRESSOF(INT1));
STOREWORDAT(+MAXINT, ADDRESSOF(INT2));
INT3 := 0;
INT4 := -1234;  INT5 := 5;
INVALIDATE(ADDRESSOF(INT6));
STOREWORDAT(0, ADDRESSOF(CHAR1));
STOREWORDAT(127, ADDRESSOF(CHAR2));  CHAR3 := 'R';
INVALIDATE(ADDRESSOF(CHAR4));
BOOL1A := FALSE;  STOREWORDAT(1, ADDRESSOF(BOOL1B));
STOREWORDAT(0, ADDRESSOF(BOOL2A));  BOOL2B := TRUE;
INVALIDATE(ADDRESSOF(BOOL3));
DAY1 := MONDAY;  DAY2 := SUNDAY;
INVALIDATE(ADDRESSOF(DAY3));
WEEK1 := MONDAY;  WEEK2 := FRIDAY;
STOREWORDAT(ORD(SUNDAY), ADDRESSOF(WEEK3A));
INVALIDATE(ADDRESSOF(WEEK3B));
NEW(PTRTOINT);
INVALIDATE(ADDRESSOF(PTRTOCHAR));
INVALIDATE(ADDRESSOF(PTRTOBOOL));
(* FAIL *)
RESET(OUTPUT);
END (* TEST1 *) .
