PROGRAM TEST2 (OUTPUT);
TYPE
   ADDRESS = INTEGER;
VAR
   REC1 : RECORD
         INT1, INT2, INT3, INT4, INT5, INT6 : INTEGER;
         REAL1, REAL2, REAL3, REAL4 : REAL;
         CHAR1, CHAR2, CHAR3, CHAR4 : CHAR;
         BOOL1, BOOL2, BOOL3 : BOOLEAN;
         PTRTOINT : ^ INTEGER;
         PTRTOREAL : ^ REAL;
         REC2 : RECORD
               INT1, INT2, INT3, INT4, INT5, INT6 : -2000..+2000;
               CHAR1, CHAR2, CHAR3, CHAR4 : 'A'..'Z';
               BOOL1A, BOOL1B : FALSE..FALSE;
               BOOL2A, BOOL2B : TRUE..TRUE;
               BOOL3 : FALSE..TRUE;
               PTRTOCHAR : ^ CHAR;
               PTRTOBOOL : ^ BOOLEAN;
               DAY1, DAY2, DAY3 : (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY);
               WEEK1, WEEK2, WEEK3A, WEEK3B : MONDAY..FRIDAY
               END
         END;

   PROCEDURE INVALIDATE (A : ADDRESS);
      BEGIN
      STOREWORDAT(-MAXINT, A);
      STOREWORDAT(WORDAT(A)-1, A);
      END (*INVALIDATE*);

BEGIN (* TEST2 *)
WITH REC1 DO
   BEGIN
   INT1 := -MAXINT;  INT2 := MAXINT;  INT3 := 0;
   INT4 := -1234;  INT5 := 5;
   INVALIDATE(ADDRESSOF(INT6));
   REAL1 := -1.23E4;  REAL2 := +4.5E-6;  REAL3 := 0.0;
   INVALIDATE(ADDRESSOF(REAL4));
   CHAR1 := CHR(0);  CHAR2 := CHR(127);  CHAR3 := 'R';
   INVALIDATE(ADDRESSOF(CHAR4));
   BOOL1 := FALSE;  BOOL2 := TRUE;
   INVALIDATE(ADDRESSOF(BOOL3));
   NEW(PTRTOREAL);
   INVALIDATE(ADDRESSOF(PTRTOINT));
   WRITE(INT4, INT6, REAL1, CHAR3:2, BOOL1:6);
   WITH REC2 DO
      BEGIN
      STOREWORDAT(-MAXINT, ADDRESSOF(INT1));
      STOREWORDAT(+MAXINT, ADDRESSOF(INT2));
      INT3 := 0;
      INT4 := -1234;  INT5 := 5;
      INVALIDATE(ADDRESSOF(INT6));
      STOREWORDAT(0, ADDRESSOF(CHAR1));
      STOREWORDAT(127, ADDRESSOF(CHAR2));  CHAR3 := 'R';
      INVALIDATE(ADDRESSOF(CHAR4));
      BOOL1A := FALSE;  STOREWORDAT(1, ADDRESSOF(BOOL1B));
      STOREWORDAT(0, ADDRESSOF(BOOL2A));  BOOL2B := TRUE;
      INVALIDATE(ADDRESSOF(BOOL3));
      NEW(PTRTOCHAR);
      INVALIDATE(ADDRESSOF(PTRTOBOOL));
      DAY1 := MONDAY;  DAY2 := SUNDAY;
      INVALIDATE(ADDRESSOF(DAY3));
      WEEK1 := MONDAY;  WEEK2 := FRIDAY;
      STOREWORDAT(ORD(SUNDAY), ADDRESSOF(WEEK3A));
      INVALIDATE(ADDRESSOF(WEEK3B));
      WRITE(INT1, CHAR3:2, BOOL1B:6, BOOL3:6);
      END;
   END;
(* FAIL *)
RESET(OUTPUT);
END (* TEST2 *) .
