#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# crnine : Executes a KDF9 binary with input on CR0
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT="~/.kdf9/"
fi

KDF9BIN=${KDF9ROOT}

BINARY=${KDF9ROOT}/Binary
DATA=${KDF9ROOT}/Data

if [ x"$1"x = xx ]
then
    echo "You have not named a binary program to be run."
    echo
    exit 1
fi

program=`basename "$1"`
program=${BINARY}/"$program"
if [ ! -r "$program" ]
then
    echo "The object code file "$program" is absent or unreadable."
    echo
    exit 2
fi

if [ x"$2"x = xx -o x"$2"x = x-x ]
then
    >${KDF9ROOT}/CR0
else
    data=${DATA}/`basename "$2" .txt`.txt
    if [ -r "$data" ]
    then
        cat "$data" > ${KDF9ROOT}/CR0
    else
        echo "The data file "$data" is absent or unreadable."
        echo
        exit 3
    fi
fi

mode=-d$3
miscellany=-m$4
if   [ "$mode" = -d ]
then
    ${KDF9BIN}/ee9 -sp -df "$miscellany" +"$program";
elif [ "$3" = - ]
then
   ${KDF9BIN}/ee9 -sp -df "$miscellany" +"$program";
elif [ "$mode" = -df ]
then
    time ${KDF9BIN}/ee9 -sp -df "$miscellany" +"$program";
else
    ${KDF9BIN}/ee9 -sp "$mode" "$miscellany"  +"$program";
fi

${KDF9BIN}/printoutput