#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# dumptape : Displays the contents of a tape drive using mtp and
#            converting the output to UTF8
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]; then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [ $# -eq 0 ]; then
    set -- "-h"
fi

while [[ "$#" -gt 0 ]]; do
    case ${1# } in
    -h | --help)
        echo "DUMPTAPE - Displays the contents of a tape drive."
        echo
        echo "Usage: dumptape TAPEDEVICE"
        echo
        echo "Note: TAPEDEVICE must exist in ${KDF9RUNTIME}"
        echo
        exit 0
        ;;
    *)
        if [ -z ${tape} ]; then
            tape="$1"
        fi
        ;;
    esac
    shift
done

TEMPORARY=/tmp
TMPFILE=${TEMPORARY}/mtp.dump

trap "rm -f ${TMPFILE}" 0 1 2 3

mtp ${tape} >${TMPFILE}

if [ -s ${TMPFILE} ]; then
    iconv -f $(file -b --mime-encoding ${TMPFILE}) -t UTF8 <${TMPFILE}
    >/dev/null
fi
