#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# dumptape : Displays the contents of a tape drive using mtp and
#            converting the output to UTF8
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "DUMPTAPE - Displays the contents of a tape drive.";
            echo;
            echo "Usage: dumptape <tape device> [T|{PQRS}{1357}{01234567}] [f|p|t|x|-] <miscellany switch or '-'>"
            echo;
            exit 0;;
    esac
fi

TMPFILE=/tmp/mtp.dump

trap "rm -f ${TMPFILE}" 0 1 2 3

mtp $1 $2 $3 $4 > ${TMPFILE}

if [ -s ${TMPFILE} ] 
then
    iconv -f `file -b --mime-encoding ${TMPFILE}` -t UTF8 < ${TMPFILE}; >/dev/null
fi

