#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# kids : Compiles and runs a Kidsgrove Algol program
#        calls kalgol to perform compilation
#------------------------------------------------------------------------

set -e
if [ -z $KDF9RUNTIME ]; then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [ $# -eq 0 ]; then
    set -- "-h"
fi

SOURCE=${KDF9RUNTIME}/Kidsgrove
DATA=${KDF9RUNTIME}/Data
TEMPORARY=/tmp

while [[ "$#" -gt 0 ]]; do
    case ${1# } in
    -h | --help)
        echo "KIDS - Compiles and runs a Kidsgrove Algol program."
        echo
        echo "Usage: kids [OPTION]... SOURCEFILE [DATAFILE]"
        echo
        echo "  -k, --kids [SEGMENT|TRACE|OPTIMISER|ORIG_SW|TEXT|NO_OPT|NO_TEST|NO_WARN|LOAD_AND_GO]"
        echo "                              define the kalgol options"
        echo "  -d, --diag [f|p|t]          define the diagnostic mode"
        echo "  -s, --state [b|p|t]         define the run state"
        echo "  -m, --misc [a|d|e|f|g|h|i|m|n|o|p|q|r|s|t|w|x|z|0|1|2|3|4|5|6|7|8|9]"
        echo "                              define the miscellaneous options"
        echo "  -nc, --no-color             do not colorize error output."
        echo "  -TP TPMODE                  define the TP mode"
        echo "  -TR TRMODE                  define the TR mode"
        echo
        echo "Note: SOURCEFILE must exist in ${SOURCE}"
        echo "      DATAFILE must exist in ${DATA}"
        echo
        exit 0
        ;;
    -s=* | --state=*)
        state=-s${1#*=}
        ;;
    -d=* | --diag=*)
        mode=-d${1#*=}
        ;;
    -nc | --no-color)
        nc='-nc'
        ;;
    -k=* | --kids=*)
        KIDSOPTS=-k${1#*=}
        ;;
    -m=* | --misc=*)
        miscellany=-m${1#*=}
        ;;
    -TR=*)
        TRmode=-TR${1#*=}
        ;;
    -TP=*)
        TPmode=-TP${1#*=}
        ;;
    *)
        if [ -z ${source} ]; then
            source="$1"
        else
            datafile="$1"
        fi
        ;;
    esac
    shift
done

if [ -z $NOCOLOR ]; then
    RED='\033[1;31m'
    YELLOW='\033[1;33m'
    NC='\033[0m' #No Color
    GREEN='\033[1;32m'
fi

echo -e "${YELLOW}Starting compilation...${NC}"
export KIDSGROVE_PEEPHOLE=n
kalgol ${KIDSOPTS/-k/-k=} "${nc}" ${source}

echo -e "${GREEN}Compilation successful. Executing${NC}"
if [ -s ${KDF9RUNTIME}/Binary/${source} ]; then
    >${KDF9RUNTIME}/settings_2.txt 
    >${KDF9RUNTIME}/settings_1.txt
    nine "${state/-s/-s=}" "${mode/-d/-d=}" "${miscellany/-m/-m=}" "${TRmode/-TR/-TR=}" "${TPmode/-TP/-TP=}" ${source} ${datafile}
else
    echo -e "${RED}Could not find executable ${KDF9RUNTIME}/Binary/${source}${NC}"
    exit 1
fi
