#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# kids : Compiles and runs a Kidsgrove Algol program
#        calls kalgol to perform compilation
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

SOURCE=${KDF9RUNTIME}/Kidsgrove
DATA=${KDF9RUNTIME}/Data

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "KIDS - Compiles and runs a Kidsgrove Algol program.";
            echo;
            echo "Usage: kids <filename> <datafile> <[f|p|t|x|-]> <miscellany switch or '-'> <TR switch> <TP switch> <[b|p|t|-]>"
            echo;
            echo "Note: <filename> must exist in ${SOURCE}"
            echo "      <datafile> must exist in ${DATA}"
            echo;
            exit 0;;
    esac
fi

kalgol $1

if [ -s ${KDF9RUNTIME}/Binary/$1 ]
then
   cat ${KDF9RUNTIME}/settings_2.txt > ${KDF9RUNTIME}/settings_1.txt
   nine $1 $2 $3 $4 $5 $6 $7
else
   exit 1
fi
