#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# kids : Compiles and runs a Kidsgrove Algol program
#        calls kalgol to perform compilation
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "kids:";
            echo "(1) : Name of file in ${KDF9RUNTIME}/Kidsgrove/ to compile and execute.";
            echo "(2) : Name of data file in ${KDF9RUNTIME}/Data/ to use or '-'.";
            echo "(3) : ee9 mode switch [f|p|t|x|-].";
            echo "(4) : ee9 miscellany switch or '-'.";
            exit 0;;
    esac
fi

DATA=${KDF9RUNTIME}/Data
WHERE=${KDF9RUNTIME}/Kidsgrove
SETTINGS=${KDF9RUNTIME}/settings

kalgol $1

if [ -s ${KDF9RUNTIME}/Binary/$1 ]
then
   cat ${KDF9RUNTIME}/settings_2.txt > ${KDF9RUNTIME}/settings_1.txt
   nine $1 $2 $3 $4
else
   exit 1
fi
