#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# neat : ???
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

USERCODE=${KDF9RUNTIME}/Assembly

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "NEAT - ?.";
            echo;
            echo "Usage: neat <filename> <sizelimit> <timelimit>"
            echo;
            echo "Note: the specified <filename> must exist in ${USERCODE}"
            echo;
            exit 0;;
    esac
fi

trap "rm -f /tmp/neat.commands /tmp/neat_tmp_[0123456789]" 0 1 2 3

if [ ! -r ${USERCODE}/$1.k3 ]
then 
   echo "Could not find $1.k3 in ${USERCODE}";
   exit 1
fi

tr  "\\r\\t" "\\n " < ${USERCODE}/$1.k3  > /tmp/neat_tmp_0
tr -s "\\n" < /tmp/neat_tmp_0 > /tmp/neat_tmp_1

cat >/tmp/neat.commands <<++++
/^ +$/d
/^ +/s//   /
10,\$s/([0123456789]) +([0123456789])/\1\2/g
10,\$s/ +;/;/g
10,\$s/; +/;/g
10,\$s/= +/=/g
10,\$s/;V +/;V/g
10,\$s/;Y +/;Y/g
10,\$s/;Y(.+) +/;Y\1/g
10,\$s/;J *S */;JS/g
10,\$s/;J *P */;JP/g
10,\$s/;J *S *P */;JSP/g
10,\$s/;S *H *A */;SHA/g
10,\$s/;Z *E *R *O *;/;ZERO;/g
10,\$s/;R *E *V *;/;REV;/g
10,\$s/;S *E *T */;SET/g
++++
sed -E -f /tmp/neat.commands /tmp/neat_tmp_1 > /tmp/neat_tmp_2

cat >/tmp/neat.commands <<++++
10,\$s/;J([^;]+);(.*)/;\\
J\\1;\\
   \\2/g

++++
sed -E -f /tmp/neat.commands /tmp/neat_tmp_2 > /tmp/neat_tmp_3

ex /tmp/neat_tmp_3  <<++++
/^|/
.+1,\$d
s/^|.*/|/
w! /tmp/neat_tmp_4
q!
++++

cat >/tmp/neat.commands <<++++
10,\$s/^ *(\**[0123456789]+);(.+)/\1;\\
   \2/
10,\$s/;J([0123456789]+)(.);/;\\
J\\1\2;\\
\\
   /g
10,\$s/;J([0123456789]+)(.)Z;/;\\
J\\1\2Z;\\
\\
   /g
10,\$s/;J([0123456789]+)(..)Z;/;\\
J\\1\2Z;\\
\\
   /g
10,\$s/;(\**[0123456789]+);/;\\
\1;\\
   /
10,\$s/;J([0123456789]+);/;\\
J\\1;\\
\\
   /g
10,\$s/;J([0123456789]*)P([0123456789]+);/;\\
J\\1P\\2;\\
   /g
10,\$s/^ +J([0123456789]+);/\\
\\
J\\1;\\
   /g
10,\$s/^ +J([0123456789]*)P([0123456789]+);/\\
J\\1P\\2;\\
   /g
10,\$s/^ +J([^;]*);/\\
J\\1;\\
   /g
10,\$s/^ *([0123456789]+);/\\
\1;\\
/
10,\$s/^ *P([0123456789]+)([^;]+);/\\
   \\
\\
P\\1\\2;/
10,\$s/=Y([^;]+);([^=][^;]+)/=Y\1;\\
   \2/g
10,\$s/     //g
10,\$s/    //g
10,\$s/;([^ ])/; \1/g
10,\$s/=Z0;( +)(.+)/=Z0;\\
   \2/g
10,\$s/JSP234;/;/g
10,\$s/JSP235;/;/g
++++
sed -E -f /tmp/neat.commands /tmp/neat_tmp_4 > /tmp/neat_tmp_5

> ${USERCODE}/$1-NEAT.k3
tr -s "\\n" < /tmp/neat_tmp_5 > /tmp/neat_tmp_6
tr "§" "\\n" < /tmp/neat_tmp_6 > ${USERCODE}/$1-NEAT.k3
sttl $1-NEAT $2 $3
mv -f ${USERCODE}/$1-NEAT.k3 ${USERCODE}/$1.k3
