#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# nine : Executes a KDF9 binary with input on TR0 or datafile.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

DATA=${KDF9RUNTIME}/Data

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "NINE - Executes a KDF9 binary with data on TR0 or <datafile>.";
            echo;
            echo "Usage: crnine <binaryname> <datafile> <[f|p|t|x|-]> <miscellany switch or '-'> <TR switch> <TP switch> <[b|p|t|-]>"
            echo;
            echo "Note: The specified <binaryname> must exist in ${KDF9RUNTIME}/Binary/"
            echo "      The specified <datafile> must exist in ${DATA}"
            echo;
            exit 0;;
    esac
fi

>${KDF9RUNTIME}/LP0
>${KDF9RUNTIME}/LP1

prog=$1
data=$2

if [ x"${prog}"x = xx ]
then
    echo "You have not named a binary program to be run."
    echo
    exit 1
fi

program=`basename "${prog}"`
program=Binary/"$program"
if [ ! -r "${KDF9RUNTIME}/$program" ]
then
    echo "The object code file "${KDF9RUNTIME}/$program" is absent or unreadable."
    echo
    exit 2
fi

if [ x"${data}"x = xx -o x"${data}"x = x-x ]
then
    >${KDF9RUNTIME}/TR0
else
    datatxt=${DATA}/`basename "${data}" ".txt"`.txt
    if [ -r "$datatxt" ]
    then
        cat "$datatxt" > ${KDF9RUNTIME}/TR1
    else
        echo "The file "$datatxt" is absent or unreadable."
        exit 3
    fi
fi

if [ x"$3"x = xx -o x"$3"x = x-x ]
then
    mode=""
else
    mode="-d$3"
fi
if [ x"$4"x = xx -o x"$4"x = x-x ]
then
    miscellany=""
else
    miscellany="-m$4"
fi
if [ x"$5"x = xx -o x"$5"x = x-x ]
then
    TRmode="-TRll"
else
    TRmode="-TR$5"
fi
if [ x"$6"x = xx -o x"$6"x = x-x ]
then
    TPmode="-TPll"
else
    TPmode="-TP$6"
fi
if [ x"$7"x = xx -o x"$7"x = x-x ]
then
    state=""
else
    state="-s$7"
fi

if [ "$mode" = -df ]
then
    time ee9 $state "$mode" "$TRmode" "$TPmode" "$miscellany" +"$program"
else
   ee9 $state "$mode" "$TRmode" "$TPmode" "$miscellany" +"$program"
fi

case $4$8 in
   *z*)
      ;;
   *-*)
      ;;
   *)
    printoutput
esac

