#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# nine_test : Calls nine specifying test mode.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "nine-test:";
            echo "(1) : Name of file in ${KDF9RUNTIME}/Binary/ to execute.";
            echo "(2) : Name of data file in ${KDF9RUNTIME}/Data/ to use or '-'.";
            echo "(3) : ee9 mode switch [f|p|t|x|-].";
            echo "(4) : ee9 miscellany switch or '-'.";
            echo "(5) : ee9 TR switch or '-'.";
            echo "(6) : ee9 TP switch or '-'.";
            exit 0;;
    esac
fi

nine "$1" "$2" "$3" "$4" "$5" "$6" t
