#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# nine_test : Calls nine specifying test mode.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "NINE_TEST - Executes a KDF9 binary with data on TR0 or <datafile> in test mode.";
            echo;
            echo "Usage: nine_test <binaryname> <datafile> <[f|p|t|x|-]> <miscellany switch or '-'> <TR switch> <TP switch>"
            echo;
            echo "Note: <binaryname> must exist in ${KDF9RUNTIME}/Binary/"
            echo "      <datafile> must exist in ${KDF9RUNTIME}/Data/"
            echo;
            exit 0;;
    esac
fi

nine "$1" "$2" "$3" "$4" "$5" "$6" t
