#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# nyne :
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]; then
   KDF9RUNTIME="$HOME/.kdf9"
fi

if [ $# -eq 0 ]; then
   set -- "-h"
fi

SOURCE=${KDF9RUNTIME}/Kidsgrove
DATA=${KDF9RUNTIME}/Data
LOGS=${KDF9RUNTIME}/logs
SETTINGS=${KDF9RUNTIME}/settings
USERCODE=${KDF9RUNTIME}/Assembly
TEMPORARY=/tmp

while [[ "$#" -gt 0 ]]; do
   case ${1# } in
   -h | --help)
      echo "NYNE - ."
      echo
      echo "Usage: nyne SOURCEFILE"
      echo
      echo "Note: SOURCEFILE must exist in ${USERCODE}"
      echo
      exit 0
      ;;
   *)
      if [ -z ${prog} ]; then
         prog="$1"
      fi
      ;;
   esac
   shift
done

if [ x$progx = xx ]; then
   echo "No program name was given."
   echo
   exit 1
elif [ ! -r ${USERCODE}/$prog.k3 ]; then
   echo "The file ${USERCODE}/$prog.k3 is absent or unreadable."
   echo
   exit 1
fi

extract_symbols ${USERCODE}/$prog.k3
if [ -r ${KDF9RUNTIME}/settings_3.txt ]
then
   cp ${KDF9RUNTIME}/settings_3.txt ${KDF9RUNTIME}/settings_1.txt
fi
cat ${KDF9RUNTIME}/settings_symbols >>${KDF9RUNTIME}/settings_1.txt

. nine $*
