#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# peep : peephole optimizer for Kidsgrove
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]; then
   KDF9RUNTIME="$HOME/.kdf9"
fi

if [ $# -eq 0 ]; then
   set -- "-h"
fi

SOURCE=${KDF9RUNTIME}/Kidsgrove
DATA=${KDF9RUNTIME}/Data
LOGS=${KDF9RUNTIME}/logs
SETTINGS=${KDF9RUNTIME}/settings
USERCODE=${KDF9RUNTIME}/Assembly

trap "rm -f /tmp/peep.commands /tmp/peep_tmp_[0123456789]" \
   0 1 2 3

while [[ "$#" -gt 0 ]]; do
   case ${1# } in
   -h | --help)
      echo "PEEP - peephole optimizer for Kidsgrove."
      echo
      echo "Usage: peep SOURCEFILE"
      echo
      echo "Note: SOURCEFILE must exist in ${USERCODE}"
      echo
      exit 0
      ;;
   *)
      if [ -z ${prog} ]; then
         prog="$1"
      fi
      ;;
   esac
   shift
done

if [ x$progx = xx ]; then
   echo "No program name was given."
   echo
   exit 1
elif [ ! -r ${USERCODE}/$prog.k3 ]; then
   echo "The file ${USERCODE}/$prog.k3 is absent or unreadable."
   echo
   exit 1
fi

tr "\\r\\t" "\\n " <${USERCODE}/$prog.k3 >/tmp/peep_tmp_0
tr -s "\\n" </tmp/peep_tmp_0 >/tmp/peep_tmp_1
a2b -L2A </tmp/peep_tmp_1 >/tmp/peep_tmp_0

cat >/tmp/peep.commands <<++++
/^ +$/d
/^ +/s//   /
10,\$s/([0123456789]) +([0123456789])/\1\2/g
10,\$s/ +;/;/g
10,\$s/; +/;/g
10,\$s/= +/=/g
10,\$s/;V +/;V/g
10,\$s/;Y +/;Y/g
10,\$s/;Y(.+) +/;Y\1/g
10,\$s/;J *S */;JS/g
10,\$s/;J *P */;JP/g
10,\$s/;J *S *P */;JSP/g
10,\$s/;S *H *A */;SHA/g
10,\$s/;Z *E *R *O *;/;ZERO;/g
10,\$s/;R *E *V *;/;REV;/g
10,\$s/;S *E *T */;SET/g
10,\$s/M\+I2;M\+I2;M\+I2;M\+I2;M\+I2;M\+I2;/SET6;=+M2;/
10,\$s/M+\I2;M\+I2;M\+I2;M\+I2;M\+I2;/SET5;=+M2;/
10,\$s/M\+I2;M\+I2;M\+I2;M\+I2;/SET4;=+M2;/
10,\$s/M\+I2;M\+I2;M\+I2;/SET3;=+M2;/
10,\$s/JSP203;/SET47;FLOAT;/g
10,\$s/SET2;JS1P231;/DUP;XF;/g
10,\$s/JP233V;//g
10,\$s/JSP244;//g
10,\$s/;SET +/;SET/g
10,\$s/SET[^;]+;=Z0;//g
++++
sed -E -f /tmp/peep.commands /tmp/peep_tmp_0 >/tmp/peep_tmp_1

cat >/tmp/peep.commands <<++++
10,\$s/SET1;SET47;FLOAT;/SETB403;SHC-10;(1.0);/g
10,\$s/SET2;SET47;FLOAT;/SETB405;SHC-10;(2.0);/g
10,\$s/SETB1;SET47;FLOAT;/SETB403;SHC-10;(1.0);/g
10,\$s/SETB2;SET47;FLOAT;/SETB405;SHC-10;(2.0);/g
10,\$s/ZERO;SET47;FLOAT;/ZERO;/g
10,\$s/;=Y0M2Q;([^;]+);M-I2;Y0M2;\+F;/;\1;+F;/
10,\$s/;=Y0M2Q;([^;]+);M-I2;Y0M2;-F;/;\1;-F;/
10,\$s/;=Y0M2Q;([^;]+);M-I2;Y0M2;\+;/;\1;+;/
10,\$s/;=Y0M2Q;([^;]+);M-I2;Y0M2;-;/;\1;-;/
++++
sed -E -f /tmp/peep.commands /tmp/peep_tmp_1 >/tmp/peep_tmp_0

cat >/tmp/peep.commands <<++++
10,\$s/ZERO;OR;//g
10,\$s/ZERO;AND;/ZERO;/g
10,\$s/REV;REV;//g
10,\$s/REV;\+F;/+F;/g
10,\$s/REV;\+;/+;/g
10,\$s/REV;XF;/XF;/g
10,\$s/REV;XD;/XD;/g
10,\$s/SET1;([^;]+);\+;/\1;NOT;NEG;/g
10,\$s/SET1;\+;/NOT;NEG;/g
10,\$s/SET1;-;/NEG;NOT;/g
10,\$s/SET1;NEG;/ZERO;NOT;/g
10,\$s/SET1;/ZERO;NOT;NEG;/g
10,\$s/SET-1;/ZERO;NOT;/g
10,\$s/SET0;/ZERO;/g
10,\$s/ZERO;NOT;NEG;REV;=M3;/=M3;ZERO;NOT;NEG;/g
10,\$s/ZERO;NOT;REV;=M3;/=M3;ZERO;NOT;/g
10,\$s/ZERO;REV;=M3;/=M3;ZERO;/g
10,\$s/ZERO;NOT;NEG;\+;/NOT;NEG;/g
10,\$s/ZERO;NOT;NEG;-;/NEG;NOT;/g
10,\$s/=Y0M2Q;([^;]+);M-I2;Y0M2;\+;/\1;+;/g
10,\$s/JSP([^;]+);EXIT1;/JP\1;/g
10,\$s/ZERO;SIGN;ABS;NEG;NOT;J([^#]+)#Z;/J\1=Z;\\
   /g
10,\$s/ZERO;SIGN;ABS;NEG;NOT;J([^=]+)=Z;/J\1#Z;\\
   /g
10,\$s/ZERO;SIGNF;ABS;NEG;NOT;J([^#]+)#Z;/J\1=Z;\\
   /g
10,\$s/ZERO;SIGNF;ABS;NEG;NOT;J([^=]+)=Z;/J\1#Z;\\
   /g
10,\$s/ZERO;SIGN;ABS;NEG;J([^#]+)#Z;/J\1#Z;\\
   /g
10,\$s/ZERO;SIGN;ABS;NEG;J([^=]+)=Z;/J\1=Z;\\
   /g
10,\$s/ZERO;SIGNF;ABS;NEG;J([^#]+)#Z;/J\1#Z;\\
   /g
10,\$s/ZERO;SIGNF;ABS;NEG;J([^=]+)=Z;/J\1=Z;\\
   /g
10,\$s/ZERO;SIGN;SHA-1;NEG;NOT;J([^=]+)=Z;/J\1GTZ;\\
   /g
10,\$s/ZERO;SIGNF;SHA-1;NEG;NOT;J([^=]+)=Z;/J\1GTZ;\\
   /g
10,\$s/ZERO;SIGNF;SHA-1;NEG;J([^=]+)=Z;/J\1LEZ;\\
   /g
10,\$s/ZERO;SIGNF;SHA-1;NEG;J([^L]+)LEZ;/J\1GEZ;\\
   /g
10,\$s/ZERO;SIGN;SHA-1;NEG;J([^=]+)=Z;/J\1LEZ;\\
   /g
10,\$s/ZERO;SIGN;SHA-1;NEG;J([^L]+)LEZ;/J\1GEZ;\\
   /g
10,\$s/ZERO;SIGN;STR;REV;ERASE;NOT;J([^=]+)=Z;/J\1LTZ;\\
   /g
10,\$s/ZERO;SIGNF;STR;REV;ERASE;NOT;J([^=]+)=Z;/J\1LTZ;\\
   /g
10,\$s/ZERO;SIGN;STR;REV;ERASE;J([^=]+)=Z;/J\1GEZ;\\
   /g
10,\$s/ZERO;SIGNF;STR;REV;ERASE;J([^=]+)=Z;/J\1GEZ;\\
   /g
10,\$s/SIGN;SHA-1;NEG;J([^=]+)=Z;/SIGN;J\1LEZ;\\
   /g
10,\$s/SIGNF;SHA-1;NEG;J([^=]+)=Z;/SIGNF;J\1LEZ;\\
   /g
10,\$s/SIGN;SHA-1;NEG;NOT;J([^=]+)=Z;/SIGN;J\1GTZ;\\
   /g
10,\$s/SIGNF;SHA-1;NEG;NOT;J([^=]+)=Z;/SIGNF;J\1GTZ;\\
   /g
10,\$s/SIGN;STR;REV;ERASE;J([^=]+)=Z;/SIGN;J\1GEZ;\\
   /g
10,\$s/SIGNF;STR;REV;ERASE;J([^=]+)=Z;/SIGNF;J\1GEZ;\\
   /g
10,\$s/SIGN;STR;REV;ERASE;NOT;J([^=]+)=Z;/SIGN;J\1LTZ;\\
   /g
10,\$s/SIGNF;STR;REV;ERASE;NOT;J([^=]+)=Z;/SIGNF;J\1LTZ;\\
   /g
10,\$s/SIGN;ABS;NEG;NOT;J([^=]+)=Z;/NEV;J\1#Z;\\
   /g
10,\$s/SIGNF;ABS;NEG;NOT;J([^=]+)=Z;/NEV;J\1#Z;\\
   /g
10,\$s/SIGN;ABS;NEG;NOT;J([^#]+)#Z;/NEV;J\1=Z;\\
   /g
10,\$s/SIGNF;ABS;NEG;NOT;J([^#]+)#Z;/NEV;J\1=Z;\\
   /g
10,\$s/ZERO;NEV;//g
++++
sed -E -f /tmp/peep.commands /tmp/peep_tmp_0 >/tmp/peep_tmp_1

cat >/tmp/peep.commands <<++++
10,\$s/ZERO;SIGN;J([^=]+)=Z;/J\1=Z;/g
10,\$s/ZERO;SIGN;J([^=]+)=Z;/J\1=Z;/g
10,\$s/ZERO;SIGN;J([^G]+)GTZ;/J\1GTZ;/g
10,\$s/ZERO;SIGN;J([^L]+)LTZ;/J\1LTZ;/g
10,\$s/ZERO;SIGN;J([^G]+)GEZ;/J\1GEZ;/g
10,\$s/ZERO;SIGN;J([^L]+)LEZ;/J\1LEZ;/g
10,\$s/ZERO;SIGNF;J([^=]+)=Z;/J\1=Z;/g
10,\$s/ZERO;SIGNF;J([^G]+)GTZ;/J\1GTZ;/g
10,\$s/ZERO;SIGNF;J([^L]+)LTZ;/J\1LTZ;/g
10,\$s/ZERO;SIGNF;J([^G]+)GEZ;/J\1GEZ;/g
10,\$s/ZERO;SIGNF;J([^L]+)LEZ;/J\1LEZ;/g
++++
sed -E -f /tmp/peep.commands /tmp/peep_tmp_1 >/tmp/peep_tmp_0

cat >/tmp/peep.commands <<++++

10,\$s/;J([^;]+);(.*)/;\\
J\\1;\\
   \\2/g
10,\$s/^ *(\**[0123456789]+);([^;]+)/\1;\\
   \2/
10,\$s/;J([0123456789]+)(.);/;\\
J\\1\2;\\
\\
   /g
10,\$s/;J([0123456789]+)(.)Z;/;\\
J\\1\2Z;\\
\\
   /g
   10,\$s/;J([0123456789]+)(..)Z;/;\\
J\\1\2Z;\\
\\
   /g
10,\$s/;(\**[0123456789]+);/;\\
\1;\\
   /
10,\$s/;J([0123456789]+);/;\\
J\\1;\\
\\
   /g
10,\$s/;J([0123456789]*)P([0123456789]+);/;\\
J\\1P\\2;\\
   /g
10,\$s/^ +J([0123456789]+);/\\
\\
J\\1;\\
   /g
10,\$s/^ +J([0123456789]*)P([0123456789]+);/\\
J\\1P\\2;\\
   /g
10,\$s/^ +J([^;]*);/\\
J\\1;\\
   /g
10,\$s/^ *([0123456789]+);/\\
\1;\\
/
10,\$s/^ *P([0123456789]+)([^;]+);/\\
   \\
\\
P\\1\\2;/
10,\$s/=Y([^;]+);([^=][^;]+)/=Y\1;\\
   \2/g
10,\$s/     //g
10,\$s/    //g
10,\$s/;([^ ])/; \1/g
10,\$s/=Z0;( +)(.+)/=Z0;\\
   \2/g
++++
sed -E -f /tmp/peep.commands /tmp/peep_tmp_0 >/tmp/peep_tmp_1

ex /tmp/peep_tmp_1 <<++++
/^|/
.+1,\$d
s/^|.*/|/
w! peep_tmp_1
q!
++++

>${USERCODE}/$1-PEEP.k3
tr -s "\\n" </tmp/peep_tmp_1 >${USERCODE}/${prog}-PEEP.k3
sttl $1-PEEP $2 $3
echo "The Usercode is in ${USERCODE}/${prog}-PEEP.k3"
echo
