#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# plt : Create or update program library magnetic tape files.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

DATA=${KDF9RUNTIME}/Data

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "PLT - Create or update program library magnetic tape files.";
            echo;
            echo "Usage: plt <filename>"
            echo;
            echo "Note: the specified <filename> must exist in ${KDF9RUNTIME}/Binary"
            echo;
            exit 0;;
    esac
fi

trap "rm -f ${DATA}/mt_test_labels.txt"  0 1 2 3

ucc PLT

if [ x$1x = xx ]
then
   >${KDF9RUNTIME}/MT1
   cat > ${DATA}/mt_test_labels.txt <<++++
-00-1234WHETLIST|
00000000        |
-00-0552EFPBEAAG|
00000000        |
-00-2339+KOUTPUT/0023004|
0-00-929PRINTEND|
0-00-777AMPEXTM4|
|
++++

   rlt mt_test_labels - zw
   nine PLT
   mtp MT1
   exit 0
fi

if [ -r ${KDF9RUNTIME}/Binary/$1 ]
then
   a2b -p2c < ${KDF9RUNTIME}/Binary/$1 > ${DATA}/$1-forPLT.txt
   cat ${KDF9RUNTIME}/Binary/$1 >> ${DATA}/$1-forPLT.txt
   nine PLT $1-forPLT.txt t - lk
   mtp MT1
else
   exit 0
fi
