#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# ports : Convert Kidsgrove Algol to Whetstone format.
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT="$HOME/.kdf9/"
fi

KDF9BIN=${KDF9ROOT}

SOURCE=${KDF9ROOT}/Kidsgrove
TARGET=${KDF9ROOT}/Whetstone

trap "rm -f /tmp/ports.commands  /tmp/ports.tmp"   \
      0 1 2 3

if [ ! -r  ${SOURCE}/$1.a60 ]
then 
      echo "Could not find $1.a60 in ${SOURCE}"; 
      exit 1
fi

cat >/tmp/ports.commands <<++++
1i\\
$1|
1,\$s/ _ /*/g
1,\$s/_ /*/g
1,\$s/_([^<>])/*\1/g
1,\$s/!library +A.+;//
1,\$s/!ALGOL/_A_L_G_O_L/g
1,\$s/!and/_a_n_d/g
1,\$s/!array/_a_r_r_a_y/g
1,\$s/!begin/_b_e_g_i_n/g
1,\$s/!boolean/_b_o_o_l_e_a_n/g
1,\$s/!Boolean/_B_o_o_l_e_a_n/g
1,\$s/!comment/_c_o_m_m_e_n_t/g
1,\$s/!do/_d_o/g
1,\$s/!else/_e_l_s_e/g
1,\$s/!end/_e_n_d/g
1,\$s/!eqv/_e_q_v/g
1,\$s/!EXIT/_E_X_I_T/g
1,\$s/!false/_f_a_l_s_e/g
1,\$s/!for/_f_o_r/g
1,\$s/!goto/_g_o_t_o/g
1,\$s/!to/_t_o/g
1,\$s/!go/_g_o/g
1,\$s/!if/_i_f/g
1,\$s/!imp/_i_m_p/g
1,\$s/!integer/_i_n_t_e_g_e_r/g
1,\$s/!KDF9/_K_D_F_9/g
1,\$s/!label/_l_a_b_e_l/g
1,\$s/!not/_n_o_t/g
1,\$s/!or/_o_r/g
1,\$s/!own/_o_w_n/g
1,\$s/!procedure/_p_r_o_c_e_d_u_r_e/g
1,\$s/!real/_r_e_a_l/g
1,\$s/!step/_s_t_e_p/g
1,\$s/!string/_s_t_r_i_n_g/g
1,\$s/!switch/_s_w_i_t_c_h/g
1,\$s/!then/_t_h_e_n/g
1,\$s/!true/_t_r_u_e/g
1,\$s/!until/_u_n_t_i_l/g
1,\$s/!value/_v_a_l_u_e/g
1,\$s/!while/_w_h_i_l_e /g
1,\$s/'library' +A.+;//
1,\$s/'ALGOL'/_A_L_G_O_L/g
1,\$s/'and'/_a_n_d/g
1,\$s/'array'/_a_r_r_a_y/g
1,\$s/'begin'/_b_e_g_i_n/g
1,\$s/'boolean'/_b_o_o_l_e_a_n/g
1,\$s/'Boolean'/_B_o_o_l_e_a_n/g
1,\$s/'comment'/_c_o_m_m_e_n_t/g
1,\$s/'do'/_d_o/g
1,\$s/'else'/_e_l_s_e/g
1,\$s/'end'/_e_n_d/g
1,\$s/'eqv'/_e_q_v/g
1,\$s/'EXIT'/_E_X_I_T/g
1,\$s/'false'/_f_a_l_s_e/g
1,\$s/'for'/_f_o_r/g
1,\$s/'go *to'/_g_o_t_o/g
1,\$s/'go'/_g_o/g
1,\$s/'if'/_i_f/g
1,\$s/'imp'/_i_m_p/g
1,\$s/'integer'/_i_n_t_e_g_e_r/g
1,\$s/'KDF9'/_K_D_F_9/g
1,\$s/'label'/_l_a_b_e_l/g
1,\$s/'not'/_n_o_t/g
1,\$s/'or'/_o_r/g
1,\$s/'own'/_o_w_n/g
1,\$s/'procedure'/_p_r_o_c_e_d_u_r_e/g
1,\$s/'real'/_r_e_a_l/g
1,\$s/'step'/_s_t_e_p/g
1,\$s/'string'/_s_t_r_i_n_g/g
1,\$s/'switch'/_s_w_i_t_c_h/g
1,\$s/'then'/_t_h_e_n/g
1,\$s/'to'/_t_o/g
1,\$s/'true'/_t_r_u_e/g
1,\$s/'until'/_u_n_t_i_l/g
1,\$s/'value'/_v_a_l_u_e/g
1,\$s/'while'/_w_h_i_l_e/g
1,\$s/!eq/=/g
1,\$s/!ge/_>/g
1,\$s/!gt/>/g
1,\$s/!le/_</g
1,\$s/!lt/</g
1,\$s/!ne/±/g
1,\$s/!=/±/g
1,\$s/!up/^/g
1,\$s/'eq'/=/g
1,\$s/'ge'/_>/g
1,\$s/'gt'/>/g
1,\$s/'le'/_</g
1,\$s/'lt'/</g
1,\$s/'ne'/±/g
1,\$s/'up'/^/g
1,\$s/%/÷/g
1,\$s/!div/÷/g
1,\$s/'div'/÷/g
1,\$s/\*/×/g
1,\$s/~/º/g
1,\$s/\\\\/º/g
1,\$s/\{/_[/g
1,\$s/}/_]/g
1,\$s/>=/_>/g
1,\$s/<=/_</g
1,\$s/!up/^/g
1,\$s/'up'/^/g
1,\$s/^\*\*\*\*$/|/
\$a\\
|
++++

cat ${SOURCE}/$1.a60 | tr -d '/r' | sed -E -f /tmp/ports.commands > ${TARGET}/$1.a60
