#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# printoutput : Prints contents of CP0/TP0/TP1/LP0/LP1 to screen.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]; then
    KDF9RUNTIME="$HOME/.kdf9"
fi

TEMPORARY=/tmp

trap "rm -f  ${TEMPORARY}/printoutput ${TEMPORARY}/format.commands" 0 1 2 3

function printline {
    echo -e "${RED}$1${GREEN}▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼${NC}"
    cat ${TEMPORARY}/printoutput
    if [ -z $EE9REGTEST ]; then echo; fi
    echo -e "${GREEN}▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲${NC}"
}

# fix any formatting issues from Kalgol
cat >${TEMPORARY}/format.commands <<++++
1,\$s/'UP'/^/g
++++

if [ -z $EE9REGTEST ]; then
    RED='\033[1;31m'
    GREEN='\033[1;32m'
    NC='\033[0m' #No Color

#    if [ -s ${KDF9RUNTIME}/CP0 ]; then
#        cat ${KDF9RUNTIME}/CP0 >${TEMPORARY}/printoutput
#        printline "CP0:"
#    fi
#
#    if [ -s ${KDF9RUNTIME}/TP0 ]; then
#        iconv -f $(file -b --mime-encoding ${KDF9RUNTIME}/TP0) -t UTF8 <${KDF9RUNTIME}/TP0 | sed -E -f ${TEMPORARY}/format.commands >${TEMPORARY}/printoutput 2>/dev/null
#        #cat ${KDF9RUNTIME}/TP0 > ${TEMPORARY}/printoutput;
#        printline "TP0:"
#    fi
#
#    if [ -s ${KDF9RUNTIME}/TP1 ]; then
#        cat ${KDF9RUNTIME}/TP1 >${TEMPORARY}/printoutput
#        printline "TP1:"
#    fi

    if [ -s ${KDF9RUNTIME}/LP0 ]; then
        iconv -f $(file -b --mime-encoding ${KDF9RUNTIME}/LP0) -t UTF8 <${KDF9RUNTIME}/LP0 | sed -E -f ${TEMPORARY}/format.commands >${TEMPORARY}/printoutput 2>/dev/null
        printline "LP0:"
    fi

    if [ -s ${KDF9RUNTIME}/LP1 ]; then
        iconv -f $(file -b --mime-encoding ${KDF9RUNTIME}/LP1) -t UTF8 <${KDF9RUNTIME}/LP1 | sed -E -f ${TEMPORARY}/format.commands >${TEMPORARY}/printoutput 2>/dev/null
        printline "LP1:"
    fi
else
    RED=''
    GREEN=''
    NC=''

#    if [ -s ${KDF9RUNTIME}/CP0 ]; then
#        cat ${KDF9RUNTIME}/CP0 >${TEMPORARY}/printoutput
#        printline "CP0:\n"
#    fi
#
#    if [ -s ${KDF9RUNTIME}/TP0 ]; then
#        cat ${KDF9RUNTIME}/TP0 >${TEMPORARY}/printoutput
#        printline "TP0:\n"
#    fi
#
#    if [ -s ${KDF9RUNTIME}/TP1 ]; then
#        cat ${KDF9RUNTIME}/TP1 >${TEMPORARY}/printoutput
#        printline "TP1:\n"
#    fi

    if [ -s ${KDF9RUNTIME}/LP0 ]; then
        cat ${KDF9RUNTIME}/LP0 >${TEMPORARY}/printoutput
        printline "LP0:\n"
    fi

    if [ -s ${KDF9RUNTIME}/LP1 ]; then
        cat ${KDF9RUNTIME}/LP1 >${TEMPORARY}/printoutput
        printline "LP1:\n"
    fi
fi
