#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# rlt : Labels tapes
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]; then
    KDF9RUNTIME="$HOME/.kdf9"
fi

TEMPORARY=/tmp

while [[ "$#" -gt 0 ]]; do
    case ${1# } in
    -h | --help)
        echo "RLT - Labels tapes."
        echo
        echo "Usage: rlt [OPTION]... [DATAFILE]"
        echo
        echo "  -d, --diag=[f|p|t]          define the diagnostic mode"
        echo "  -m, --misc [a|d|e|f|g|h|i|m|n|o|p|q|r|s|t|w|x|z|0|1|2|3|4|5|6|7|8|9]"
        echo "                              define the miscellaneous options"
        echo "  -TP TPMODE                  define the TP mode"
        echo "  -TR TRMODE                  define the TR mode"
        echo
        echo "Note: DATAFILE must exist in ${DATA}"
        echo
        exit 0
        ;;
    -d=* | --diag=*)
        mode=-d${1#*=}
        ;;
    -m=* | --misc=*)
        miscellany=-m${1#*=}
        ;;
    -TR=*)
        TRmode=-TR${1#*=}
        ;;
    -TP=*)
        TPmode=-TP${1#*=}
        ;;
    *)
        if [ -z ${datafile} ]; then
            datafile="$1"
        fi
        ;;
    esac
    shift
done

>${KDF9RUNTIME}/MT0
>${KDF9RUNTIME}/MT1
>${KDF9RUNTIME}/MT2
>${KDF9RUNTIME}/MT3
>${KDF9RUNTIME}/MT4
>${KDF9RUNTIME}/MT5
>${KDF9RUNTIME}/ST0

# Have to run RLT in "test program" state.
nine_test "${mode/-d/-d=}" "${miscellany/-m/-m=}" "${TRmode/-TR/-TR=}" "${TPmode/-TP/-TP=}" RLT ${datafile:-RLT_data}
