#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# rtl : Labels tapes
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT="~/.kdf9/"
fi

KDF9BIN=${KDF9ROOT}

BINARY=${KDF9ROOT}/Binary

>${KDF9ROOT}/MT0
>${KDF9ROOT}/MT1
>${KDF9ROOT}/MT2
>${KDF9ROOT}/MT3
>${KDF9ROOT}/MT4
>${KDF9ROOT}/MT5
>${KDF9ROOT}/ST0
${KDF9BIN}/nine_test ${BINARY}/RLT ${1:-RLT_data} $2 $3 $4
