#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# rlt : Labels tapes
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [[ "$#" -gt 0 ]]; then
    case $1 in
        -h|--help) 
            echo "RLT - Labels tapes.";
            echo;
            echo "Usage: rlt <datafile> <[f|p|t|x|-]> <miscellany switch or '-'> <TR switch> <TP switch>"
            echo;
            echo "Note: <datafile> must exist in ${KDF9RUNTIME}/Data"
            echo;
            exit 0;;
    esac
fi

>${KDF9RUNTIME}/MT0
>${KDF9RUNTIME}/MT1
>${KDF9RUNTIME}/MT2
>${KDF9RUNTIME}/MT3
>${KDF9RUNTIME}/MT4
>${KDF9RUNTIME}/MT5
>${KDF9RUNTIME}/ST0
nine_test RLT ${1:-RLT_data} $2 $3 $4 $5
