#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# strop0 : Convert normal keyboard characters to Kidsgrove Algol format.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

TARGET=${KDF9RUNTIME}/Kidsgrove

trap "rm -f /tmp/strop0.commands  /tmp/strop0.tmp"   \
      0 1 2 3

if [ ! -r $1.a60 ]
then 
      echo "Could not find $1.a60"; 
      exit 1
fi

cat >/tmp/strop0.commands <<++++
1i\\
$1|
1,\$s/!=/±/g
1,\$s/%/÷/g
1,\$s/\*/×/g
1,\$s/~/º/g
1,\$s/\\\\/º/g
1,\$s/\{/_[/g
1,\$s/}/_]/g
1,\$s/>=/_>/g
1,\$s/<=/_</g
1,\$s/^\*\*\*\*$/|/
\$a\\
|
++++

cat $1.a60 | tr -d '/r' | sed -E -f /tmp/strop0.commands > ${TARGET}/$1.a60
