#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# sttl : Set the store size and time limit on Usercode files.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

USERCODE=${KDF9RUNTIME}/Assembly

trap "rm -f /tmp/STTL.commands /tmp/STTL_tmp"   \
      0 1 2 3

cat >/tmp/STTL.commands <<++++
/^ST *.+ *; *TL *.+ *;/s//ST${2:-7680}; TL${3:-3000};/
++++

if sed -E -f /tmp/STTL.commands ${USERCODE}/$1.k3 > /tmp/STTL_tmp
then
   mv -f /tmp/STTL_tmp ${USERCODE}/$1.k3
else
   echo "**** FAILURE when correcting ST and TL in ${USERCODE}/$1.k3"
fi
