#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# tsp : Runs the KDF9 director.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

trap ">${KDF9RUNTIME}/FW0"  \
      0 1 2 3

TSD=${KDF9RUNTIME}/Binary/KKT40E007UPU

cat ${KDF9RUNTIME}/Settings/FW0_for_Director > ${KDF9RUNTIME}/FW0

mode=-d$1
miscellany=-m$2

if [ "$mode" = "-d" ]
then
    ee9 -sb -df -TRkk -TPll  +${TSD};
elif [ $mode = -df ]
then
    time ee9 -sb -df -TRkk -TPll  +${TSD};
elif [ $miscellany = -m ]
then
    ee9 -sb "$mode" -TRkk -TPll  +${TSD};
else
    ee9 -sb "$mode" "$miscellany"  -TRkk -TPll +${TSD};
fi

printoutput