#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# tsp : Runs the KDF9 director.
#------------------------------------------------------------------------

if [ -z $KDF9RUNTIME ]
then
    KDF9RUNTIME="$HOME/.kdf9"
fi

FW0FILES=${KDF9RUNTIME}/FW0Files

while [[ "$#" -gt 0 ]]; do
    case ${1# } in
        -h|--help) 
            echo "TSD - Runs the director.";
            echo;
            echo "Usage: tsd [OPTION]..."
            echo;
            echo "  -d, --diag [f|p|t]          define the diagnostic mode";
            echo "  -m, --misc MISC             define the miscellaneous options";
            echo;
            exit 0;;
        -d=*|--diag=*)
            mode=-d${1#*=};
            ;;
        -m=*|--misc=*)
            miscellany=-m${1#*=};
            ;;
        *)
            ;;
    esac
    shift;
done

trap ">${KDF9RUNTIME}/FW0" 0 1 2 3

cat ${FW0FILES}/FW0_for_Director > ${KDF9RUNTIME}/FW0

if [ $mode = -df ]
then
    time ee9 -sb "$mode" "$miscellany" -TRkk -TPll  +Binary/KKT40E007UPU;
else
    ee9 -sb "$mode" "$miscellany" -TRkk -TPll +Binary/KKT40E007UPU;
fi

printoutput