#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# tsdnine : Executes a KDF9 binary in the director.
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT="~/.kdf9/"
fi

KDF9BIN=${KDF9ROOT}

DATA=${KDF9ROOT}/Data
BINARY=${KDF9ROOT}/Binary

trap "rm -f /tmp/$1.pblk; exit 2" 1 2 3

if [ x$1x = xx ]
then
   echo; echo "No program name was given."; echo
   exit 1
fi

# Set up a set of labelled tapes, including at least one ZERO (scratch) tape.
cat > ${DATA}/TSD_tape_labels.txt <<++++
-00-1478        |
-66-1909EXAMTIME|
-00-0552EFPBEAAG|
        MS-DUMP.|
-00-2339+KOUTPUT/0023004|
0-00-929PRINTEND|
0-00-777AMPEXTM4|
|
++++

${KDF9BIN}/rlt $TSD_tape_labels - z

# Create a call tape from the binary program.
${KDF9BIN}/a2b -p2c P < ${BINARY}/$1  > /tmp/$1.pblk

# Combine the call tape and the binary in a single paper tape file.
cat ${BINARY}/$1 >> /tmp/$1.pblk
mv /tmp/$1.pblk ${KDF9ROOT}/TR1

#ucc PLT
#nine PLT $1 - z kk

if [ x"$2"x = xx -o x"$2"x = x-x ]
then
   : no data file
else
   # Add the data file to the end of the paper tape.
   ${KDF9BIN}/a2b -L2p < ${DATA}/$2.txt >> ${KDF9ROOT}/TR1
fi

# Run Director.
${KDF9BIN}/tsd $3 $4 $5 $6
