#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# whet : Executes a Whetstone Algol program.
#------------------------------------------------------------------------
if [ -z $KDF9RUNTIME ]; then
    KDF9RUNTIME="$HOME/.kdf9"
fi

if [ $# -eq 0 ]; then
    set -- "-h"
fi

SOURCE=${KDF9RUNTIME}/Whetstone
FW0FILES=${KDF9RUNTIME}/FW0Files
TEMPORARY=/tmp

while [[ "$#" -gt 0 ]]; do
    case ${1# } in
    -h | --help)
        echo "WHET - Executes a Whetstone Algol program."
        echo
        echo "Usage: whet [OPTION]... SOURCEFILE"
        echo
        echo "  -d, --diag [f|p|t]          define the diagnostic mode"
        echo "  -m, --misc [a|d|e|f|g|h|i|m|n|o|p|q|r|s|t|w|x|z|0|1|2|3|4|5|6|7|8|9]"
        echo "                              define the miscellaneous options"
        echo "  -TP TPMODE                  define the TP mode"
        echo "  -TR TRMODE                  define the TR mode"
        echo
        echo "Note: SOURCEFILE must exist in ${SOURCE}"
        echo
        exit 0
        ;;
    -d=* | --diag=*)
        mode=-d${1#*=}
        ;;
    -m=* | --misc=*)
        miscellany=-m${1#*=}
        ;;
    *)
        if [ -z ${source} ]; then
            source="$1"
        fi
        ;;
    esac
    shift
done

trap ">${KDF9RUNTIME}/FW0" 0 1 2 3

if [ x"$source"x = xx ]; then
    echo "You have not named a Whetstone Algol program to be run."
    echo
    exit 1
fi

program=$(basename "$source" ".a60").a60
program=${SOURCE}/"$program"
if [ -r "$program" ]; then
    cat "$program" >${KDF9RUNTIME}/TR1
else
    echo "The source file "$program" is absent or unreadable."
    echo
    exit 2
fi

cat ${FW0FILES}/FW0_for_Whetstone >${KDF9RUNTIME}/FW0

if [ "$mode" = -df ]; then
    time ee9 -sp ${mode} "$miscellany" +Binary/KMW0201--UPU
else
    ee9 -sp "$mode" "$miscellany" +Binary/KMW0201--UPU
fi

case $miscellany in
*z*) ;;

*)
    printoutput
    ;;
esac
