#!/bin/bash
#------------------------------------------------------------------------
#    This file is part of ee9.
#
#    ee9 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ee9 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ee9.  If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------
#------------------------------------------------------------------------
# whet : Executes a Whetstone Algol program.
#------------------------------------------------------------------------

KDF9ROOT=${KDF9RUNTIME}

if [ -z $KDF9ROOT ]
then
    KDF9ROOT="~/.kdf9/";
fi

KDF9BIN=$KDF9ROOT

trap ">${KDF9ROOT}/FW0"  \
      0 1 2 3

BINARY=${KDF9ROOT}/Binary
SOURCE=${KDF9ROOT}/Whetstone
FW0FILES=${KDF9ROOT}/FW0Files

if [ x"$1"x = xx ]
then
    echo "You have not named a Whetstone Algol program to be run."
    echo
    exit 1
fi

program=`basename "$1" ".a60"`.a60
program=${SOURCE}/"$program"
if [ -r "$program" ]
then
    cat "$program" > ${KDF9ROOT}/TR1
else
    echo "The source file "$program" is absent or unreadable."
    echo
    exit 2
fi

cat ${FW0FILES}/FW0_for_Whetstone > ${KDF9ROOT}/FW0

mode=-d$2
miscellany=-m$3

if   [ "$mode" = -d ]
then
    ${KDF9BIN}/ee9 +${BINARY}/KMW0201--UPU;
elif [ "$mode" = -d- ]
then
    ${KDF9BIN}/ee9 -sp -df "$miscellany" +${BINARY}/KMW0201--UPU;
elif [ "$mode" = -df ]
then
    time ${KDF9BIN}/ee9 -sp -df "$miscellany" +${BINARY}/KMW0201--UPU;
else
    ${KDF9BIN}/ee9 -sp "$mode" "$miscellany" +${BINARY}/KMW0201--UPU;
fi

${KDF9BIN}/printoutput
